import type { Marco } from "@/lib/glossario";

// Linha do tempo da home: dinheiro e dólar, Brasil, crises, investimentos, tecnologia e internet,
// inteligência artificial e cripto, num fio só. Conta como chegamos ao mundo em que dolarizar parte
// do patrimônio virou possível e sensato. Em ordem cronológica; `antecedentes` só aponta para marcos
// anteriores desta lista (é a linhagem que acende ao passar o mouse). Datas conferidas em 07/out/2026.
export const LINHA_DO_TEMPO: Marco[] = [
  {
    slug: "1792-nasce-o-dolar",
    ano: 1792,
    data: "2 de abril de 1792",
    categoria: "Dinheiro e dólar",
    titulo: "Nasce o dólar",
    resumo: "O Congresso americano cria a casa da moeda e define o dólar como a unidade de conta do país, lastreado em prata e ouro.",
    texto: [
      "Os Estados Unidos tinham acabado de nascer e ainda usavam moedas espanholas, inglesas e papéis de cada estado. A Lei da Cunhagem, assinada por George Washington, pôs ordem nisso: criou a Casa da Moeda na Filadélfia e definiu o dólar por uma quantidade fixa de metal.",
      "Era uma moeda de um país agrícola e periférico. Levou mais de 150 anos para virar a régua do mundo.",
      "Por que importa hoje: o dólar não nasceu forte. Ele ganhou o posto com instituições, tamanho de mercado e regras previsíveis, e é exatamente isso que o investidor compra quando leva parte do patrimônio para lá.",
    ],
    verbetes: ["cambio", "padrao-ouro"],
    fonte: "Coinage Act de 1792; U.S. Mint",
  },
  {
    slug: "1792-acordo-de-buttonwood",
    ano: 1792,
    data: "17 de maio de 1792",
    categoria: "Investimentos",
    titulo: "O acordo debaixo da árvore",
    resumo: "Vinte e quatro corretores assinam em Nova York o acordo que dá origem à Bolsa de Nova York.",
    texto: [
      "Diz a tradição que foi debaixo de um plátano, na Wall Street. Os 24 corretores combinaram negociar só entre eles e cobrar uma comissão mínima. Era um clube pequeno para comprar e vender títulos do governo e ações de alguns bancos.",
      "Desse papel saiu a Bolsa de Nova York, que dois séculos depois concentra boa parte do valor de todas as empresas listadas do planeta.",
      "Por que importa hoje: quando você compra uma ação americana, entra num mercado com mais de 230 anos de regras acumuladas. Tamanho e profundidade não garantem lucro, mas dão opções que a bolsa brasileira não tem.",
    ],
    verbetes: ["sp-500", "diversificacao"],
    antecedentes: ["1792-nasce-o-dolar"],
    fonte: "NYSE; Buttonwood Agreement",
  },
  {
    slug: "1896-indice-dow-jones",
    ano: 1896,
    data: "26 de maio de 1896",
    categoria: "Investimentos",
    titulo: "O primeiro termômetro da bolsa",
    resumo: "Charles Dow publica a média de 12 ações industriais, o índice que vira sinônimo de bolsa americana.",
    texto: [
      "Antes, para saber se o mercado tinha subido, era preciso olhar ação por ação. Charles Dow somou o preço de 12 empresas industriais e dividiu por 12. Simples assim, e funcionou: pela primeira vez o mercado inteiro cabia num número.",
      "Das 12 originais, nenhuma está mais no índice. As empresas mudam, o índice fica.",
      "Por que importa hoje: medir o mercado por um índice é o primeiro passo para comprar o mercado inteiro, sem escolher ação por ação. É a semente dos fundos de índice e dos ETFs que você usa para investir lá fora.",
    ],
    verbetes: ["sp-500", "gestao-passiva"],
    antecedentes: ["1792-acordo-de-buttonwood"],
    fonte: "S&P Dow Jones Indices",
  },
  {
    slug: "1900-padrao-ouro-nos-eua",
    ano: 1900,
    data: "14 de março de 1900",
    categoria: "Dinheiro e dólar",
    titulo: "O dólar se amarra ao ouro",
    resumo: "A Lei do Padrão-Ouro fixa o dólar a uma quantidade de ouro e encerra o debate sobre a prata.",
    texto: [
      "Durante décadas, os Estados Unidos brigaram sobre o lastro da moeda: ouro, prata ou os dois. Em 1900, o ouro ganhou. Cada dólar passou a ser trocável por uma quantidade fixa do metal, como já acontecia com a libra esterlina.",
      "O padrão-ouro dava uma promessa clara: o governo não podia imprimir à vontade. O custo era a rigidez. Em crise, a economia não tinha folga para respirar.",
      "Por que importa hoje: toda a história do dólar no século 20 é a de afrouxar essa amarra. Entender de onde ela veio ajuda a ler as discussões atuais sobre ouro, bitcoin e moedas com oferta limitada.",
    ],
    verbetes: ["padrao-ouro", "inflacao"],
    antecedentes: ["1792-nasce-o-dolar"],
    fonte: "Gold Standard Act de 1900; Federal Reserve History",
  },
  {
    slug: "1913-nasce-o-fed",
    ano: 1913,
    data: "23 de dezembro de 1913",
    categoria: "Dinheiro e dólar",
    titulo: "Nasce o Fed",
    resumo: "Depois do pânico bancário de 1907, os Estados Unidos criam o seu banco central, o Federal Reserve.",
    texto: [
      "Em 1907, uma corrida aos bancos em Nova York só foi contida porque o banqueiro J. P. Morgan juntou os colegas e pôs dinheiro do próprio bolso. O país percebeu que não dava para depender de um homem. Seis anos depois, o presidente Woodrow Wilson assinou a lei que criou o Federal Reserve.",
      "O Fed virou o emprestador de última instância do sistema e, com o tempo, o banco central mais influente do mundo.",
      "Por que importa hoje: os juros do Fed definem o custo do dinheiro no planeta inteiro. Quando ele sobe ou corta, mexe no dólar, nas bolsas e no prêmio que o Brasil paga para se financiar.",
    ],
    verbetes: ["banco-central", "treasury"],
    antecedentes: ["1900-padrao-ouro-nos-eua"],
    fonte: "Federal Reserve Act; Federal Reserve History",
  },
  {
    slug: "1929-crash-de-nova-york",
    ano: 1929,
    data: "29 de outubro de 1929",
    categoria: "Crises",
    titulo: "O crash de 1929",
    resumo: "A bolsa de Nova York desaba em poucos dias e abre caminho para a Grande Depressão.",
    texto: [
      "A década de 1920 foi de euforia, com muita gente comprando ação a crédito. Em outubro de 1929, o castelo caiu: a quinta-feira 24 e a terça-feira 29 entraram para a história. O índice Dow Jones perderia perto de 89% entre o pico de 1929 e o fundo de 1932.",
      "Quem comprou no topo só recuperou o valor nominal em 1954, 25 anos depois, sem contar os dividendos.",
      "Por que importa hoje: crise não é exceção, é parte do jogo, inclusive no mercado americano. Diversificar não evita quedas, mas evita depender de um único mercado, uma única moeda e um único momento de entrada.",
    ],
    verbetes: ["volatilidade", "diversificacao", "market-timing"],
    antecedentes: ["1896-indice-dow-jones", "1913-nasce-o-fed"],
    fonte: "S&P Dow Jones Indices; Federal Reserve History",
  },
  {
    slug: "1933-ouro-recolhido-nos-eua",
    ano: 1933,
    data: "5 de abril de 1933",
    categoria: "Dinheiro e dólar",
    titulo: "Até os americanos tiveram o ouro recolhido",
    resumo: "Franklin Roosevelt obriga os cidadãos a entregar o ouro ao Fed. No ano seguinte, o dólar é desvalorizado frente ao metal.",
    texto: [
      "Em plena Depressão, um decreto presidencial mandou os americanos entregarem moedas e barras de ouro ao Fed, ao preço oficial de US$ 20,67 a onça. Em janeiro de 1934, o governo subiu o preço para US$ 35. Na prática, o dólar perdeu 41% do valor em ouro de uma canetada.",
      "Foi a forma de soltar a política monetária e combater a deflação. Funcionou para a economia; quem guardava ouro em casa não teve escolha.",
      "Por que importa hoje: risco de regra existe em qualquer país, inclusive nos Estados Unidos. A diferença está na frequência e na força dos episódios, e é por isso que o curso fala em diluir jurisdição, não em achar um lugar sem risco.",
    ],
    verbetes: ["padrao-ouro", "banco-central"],
    antecedentes: ["1929-crash-de-nova-york", "1913-nasce-o-fed"],
    fonte: "Executive Order 6102; Gold Reserve Act de 1934",
  },
  {
    slug: "1934-nasce-a-sec",
    ano: 1934,
    data: "6 de junho de 1934",
    categoria: "Investimentos",
    titulo: "O mercado ganha um xerife",
    resumo: "Os Estados Unidos criam a SEC, a comissão que fiscaliza a bolsa e obriga as empresas a abrir as contas.",
    texto: [
      "Depois de 1929, ficou claro que boa parte da euforia tinha sido alimentada por informação ruim e manipulação. A lei de 1934 criou a SEC e obrigou as empresas listadas a publicar balanços periódicos auditados.",
      "A CVM brasileira, de 1976, segue a mesma lógica: regra clara e informação pública antes de pedir o dinheiro do investidor.",
      "Por que importa hoje: quando você investe por um ETF americano, está protegido por esse arcabouço de divulgação e fiscalização. Não elimina perdas, mas reduz o risco de não saber o que está comprando.",
    ],
    verbetes: ["etf", "sp-500"],
    antecedentes: ["1929-crash-de-nova-york"],
    fonte: "Securities Exchange Act de 1934; SEC",
  },
  {
    slug: "1942-nasce-o-cruzeiro",
    ano: 1942,
    data: "1º de novembro de 1942",
    categoria: "Brasil",
    titulo: "O réis vira cruzeiro",
    resumo: "Getúlio Vargas troca o réis pelo cruzeiro. É a primeira das oito moedas que o Brasil teria até o real.",
    texto: [
      "O decreto saiu em 5 de outubro e valeu a partir de 1º de novembro: mil réis passaram a ser um cruzeiro. Parecia só uma troca de nome. Foi o começo de 52 anos em que o país mudaria de moeda oito vezes.",
      "Pelas conversões oficiais do Banco Central, um real de hoje equivale a 2,75 quatrilhões de cruzeiros de 1942.",
      "Por que importa hoje: a moeda que você guarda é uma decisão política, e no Brasil essa decisão mudou muitas vezes. O real é a mais duradoura delas, mas o histórico explica por que concentrar tudo numa moeda só é uma aposta.",
    ],
    verbetes: ["hiperinflacao", "inflacao", "cambio"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:10" },
    fonte: "Decreto-Lei 4.791/1942; BCB, Museu de Valores",
  },
  {
    slug: "1944-bretton-woods",
    ano: 1944,
    data: "1º a 22 de julho de 1944",
    categoria: "Dinheiro e dólar",
    titulo: "Bretton Woods: o dólar vira o centro do mundo",
    resumo: "Quarenta e quatro países, o Brasil entre eles, prendem suas moedas ao dólar, e o dólar ao ouro a US$ 35 a onça.",
    texto: [
      "Num hotel em New Hampshire, ainda durante a guerra, os aliados desenharam a ordem monetária do pós-guerra. Cada moeda teria uma cotação fixa contra o dólar, e só o dólar seria trocável por ouro, a US$ 35 a onça, para outros bancos centrais. Ali nasceram também o FMI e o Banco Mundial.",
      "A libra esterlina, que tinha sido a moeda central do século 19, passou o bastão.",
      "Por que importa hoje: é por causa desse arranjo que petróleo, soja, minério e boa parte do comércio mundial são cotados em dólar até hoje. Dolarizar parte do patrimônio é usar a régua em que o mundo mede quase tudo.",
    ],
    verbetes: ["bretton-woods", "padrao-ouro", "cambio"],
    antecedentes: ["1933-ouro-recolhido-nos-eua", "1913-nasce-o-fed"],
    noCurso: { modulo: 0, aula: 1, tempo: "3:49" },
    fonte: "FMI; Federal Reserve History",
  },
  {
    slug: "1947-transistor",
    ano: 1947,
    data: "dezembro de 1947",
    categoria: "Tecnologia e internet",
    titulo: "O transistor",
    resumo: "No Bell Labs, John Bardeen e Walter Brattain fazem funcionar o primeiro transistor, a peça básica de toda a eletrônica.",
    texto: [
      "Antes dele, computadores usavam válvulas que esquentavam, queimavam e ocupavam salas inteiras. O transistor fazia o mesmo papel de chave liga e desliga, só que pequeno, frio e confiável. Bardeen, Brattain e William Shockley levaram o Nobel de Física em 1956.",
      "Tudo o que veio depois, do chip ao celular, é a história de colocar mais transistores em menos espaço.",
      "Por que importa hoje: a tecnologia virou o maior setor da bolsa americana e quase não existe na brasileira. Quem fica só no Brasil fica de fora da cadeia que nasceu aqui.",
    ],
    verbetes: ["internet", "sp-500"],
    fonte: "Nokia Bell Labs; Fundação Nobel",
  },
  {
    slug: "1950-teste-de-turing",
    ano: 1950,
    data: "outubro de 1950",
    categoria: "Inteligência artificial",
    titulo: "Máquinas podem pensar?",
    resumo: "Alan Turing propõe um jogo para testar se uma máquina conversa como gente. A pergunta guia a inteligência artificial até hoje.",
    texto: [
      "Turing trocou a pergunta filosófica por uma prática: se, numa conversa por escrito, você não consegue distinguir a máquina de uma pessoa, que diferença faz? O artigo saiu na revista Mind e ficou conhecido como o teste de Turing.",
      "Por décadas, o teste pareceu distante. Os modelos de linguagem dos anos 2020 o puseram de volta no centro do debate.",
      "Por que importa hoje: a inteligência artificial é hoje um dos motores da bolsa americana. Entender que a ideia tem 75 anos ajuda a separar a tecnologia de longo prazo da euforia de cada ciclo.",
    ],
    verbetes: ["inteligencia-artificial"],
    fonte: "A. M. Turing, Computing Machinery and Intelligence, Mind",
  },
  {
    slug: "1952-markowitz-e-a-diversificacao",
    ano: 1952,
    data: "março de 1952",
    categoria: "Investimentos",
    titulo: "Diversificar vira conta",
    resumo: "Harry Markowitz mostra que o risco de uma carteira depende de como os ativos se movem juntos, não só de cada um.",
    texto: [
      "Todo mundo sabia que não se põem todos os ovos na mesma cesta. Markowitz, então um estudante de doutorado em Chicago, mostrou quanto isso vale: dois ativos arriscados que sobem e descem em momentos diferentes podem formar uma carteira menos arriscada que cada um deles. O trabalho rendeu o Nobel em 1990.",
      "A carteira 60/40, com ações e títulos, e a ideia de juntar países e moedas diferentes descendem dessa intuição.",
      "Por que importa hoje: dolarizar parte do patrimônio é aplicar Markowitz à escala de países. O que diversifica não é ter muitos ativos brasileiros, é ter ativos que não dependem todos da mesma economia.",
    ],
    verbetes: ["diversificacao", "carteira-60-40", "volatilidade"],
    antecedentes: ["1929-crash-de-nova-york"],
    fonte: "H. Markowitz, Portfolio Selection, Journal of Finance; Fundação Nobel",
  },
  {
    slug: "1956-conferencia-de-dartmouth",
    ano: 1956,
    data: "verão de 1956",
    categoria: "Inteligência artificial",
    titulo: "A inteligência artificial ganha nome",
    resumo: "Num encontro de verão na faculdade de Dartmouth, um grupo de pesquisadores funda o campo da inteligência artificial.",
    texto: [
      "John McCarthy, Marvin Minsky, Claude Shannon e Nathaniel Rochester escreveram a proposta: cada aspecto da inteligência poderia ser descrito com precisão a ponto de uma máquina simulá-lo. O termo inteligência artificial vem daí.",
      "O otimismo era enorme e o caminho foi longo, com décadas de avanços e frustrações, os chamados invernos da inteligência artificial.",
      "Por que importa hoje: ciclos de euforia e desânimo com tecnologia se repetem, e as bolsas acompanham. Ter exposição a essa fronteira pela diversificação é diferente de apostar tudo no auge de um ciclo.",
    ],
    verbetes: ["inteligencia-artificial"],
    antecedentes: ["1950-teste-de-turing"],
    fonte: "Proposta do Dartmouth Summer Research Project on Artificial Intelligence",
  },
  {
    slug: "1957-nasce-o-sp-500",
    ano: 1957,
    data: "4 de março de 1957",
    categoria: "Investimentos",
    titulo: "Nasce o S&P 500",
    resumo: "A Standard & Poor's lança um índice com 500 grandes empresas americanas, ponderado pelo valor de mercado de cada uma.",
    texto: [
      "Com 500 empresas e peso proporcional ao tamanho de cada uma, o índice passou a representar o grosso da bolsa americana de um jeito que as 30 ações do Dow não conseguiam. Virou a régua que gestores do mundo inteiro tentam bater.",
      "A composição mudou com a economia: hoje a tecnologia pesa perto de um terço do índice.",
      "Por que importa hoje: o S&P 500 é a referência das comparações do curso, como a de dólar mais S&P contra o CDI. Comprá-lo inteiro, por um fundo de índice ou ETF, é a forma mais direta de ter um pedaço da economia americana.",
    ],
    verbetes: ["sp-500", "gestao-passiva", "etf"],
    antecedentes: ["1896-indice-dow-jones"],
    noCurso: { modulo: 0, aula: 3, tempo: "17:57" },
    fonte: "S&P Dow Jones Indices",
  },
  {
    slug: "1958-circuito-integrado",
    ano: 1958,
    data: "12 de setembro de 1958",
    categoria: "Tecnologia e internet",
    titulo: "O chip",
    resumo: "Jack Kilby, da Texas Instruments, demonstra o primeiro circuito integrado. Meses depois, Robert Noyce chega a uma versão em silício.",
    texto: [
      "Em vez de soldar transistores um a um, Kilby construiu vários componentes num único pedaço de material. Noyce, na Fairchild, resolveu a fabricação em silício. Nascia o chip, e com ele a possibilidade de produzir eletrônica em escala.",
      "Noyce fundaria a Intel dez anos depois. O Vale do Silício tem esse nome por causa dessa pastilha.",
      "Por que importa hoje: os fabricantes e projetistas de chips estão entre as maiores empresas do mundo. É um setor praticamente ausente da B3, e uma das razões de a bolsa americana ter outra cara.",
    ],
    verbetes: ["internet", "diversificacao"],
    antecedentes: ["1947-transistor"],
    fonte: "Texas Instruments; Computer History Museum",
  },
  {
    slug: "1960-dilema-de-triffin",
    ano: 1960,
    categoria: "Dinheiro e dólar",
    titulo: "O dilema de Triffin",
    resumo: "O economista Robert Triffin avisa que o sistema de Bretton Woods tem um defeito de fábrica.",
    texto: [
      "Para o mundo ter dólares de reserva, os Estados Unidos precisavam mandar dólares para fora, gastando mais do que recebiam. Só que, quanto mais dólares havia lá fora, menos crível ficava a promessa de trocar cada um por ouro a US$ 35. Triffin descreveu o problema no livro Gold and the Dollar Crisis.",
      "A previsão se cumpriu: ao longo da década, o ouro americano foi saindo e a desconfiança crescendo.",
      "Por que importa hoje: o dilema continua vivo. O mundo quer dólares e títulos do Tesouro americano, e isso permite aos Estados Unidos se financiar barato, mas também alimenta a dúvida recorrente sobre a dívida americana.",
    ],
    verbetes: ["bretton-woods", "treasury", "divida-publica"],
    antecedentes: ["1944-bretton-woods"],
    fonte: "R. Triffin, Gold and the Dollar Crisis",
  },
  {
    slug: "1964-nasce-o-banco-central",
    ano: 1964,
    data: "31 de dezembro de 1964",
    categoria: "Brasil",
    titulo: "Nasce o Banco Central do Brasil",
    resumo: "A reforma bancária cria o Banco Central e o Conselho Monetário Nacional. No mesmo ano, chega a correção monetária.",
    texto: [
      "Até então, o papel de banco central era dividido entre a Sumoc e o Banco do Brasil. A Lei 4.595 criou o Banco Central do Brasil. Meses antes, em julho, a Lei 4.357 tinha criado as ORTN, títulos públicos corrigidos pela inflação.",
      "A correção monetária ajudou a conviver com a inflação, mas também a perpetuá-la: com tudo indexado, a inflação de ontem virava a de amanhã. Esse vício só seria quebrado em 1994.",
      "Por que importa hoje: um banco central com regras claras é o que dá valor à moeda. O caminho do Brasil até isso foi longo, e o prêmio que o mercado cobra do país ainda reflete essa história.",
    ],
    verbetes: ["banco-central", "inflacao", "divida-publica"],
    antecedentes: ["1942-nasce-o-cruzeiro"],
    fonte: "Lei 4.595/1964; Lei 4.357/1964; Banco Central do Brasil",
  },
  {
    slug: "1968-nasce-o-ibovespa",
    ano: 1968,
    data: "2 de janeiro de 1968",
    categoria: "Investimentos",
    titulo: "Nasce o Ibovespa",
    resumo: "A Bolsa de São Paulo começa a calcular o seu índice, com base de 100 pontos.",
    texto: [
      "O Ibovespa passou a medir uma carteira teórica das ações mais negociadas da bolsa paulista. Desde então, atravessou seis trocas de moeda, hiperinflação e vários cortes de zeros, o que torna a série em reais difícil de comparar ao longo do tempo.",
      "A composição espelha a economia brasileira: bancos, petróleo, mineração e outras commodities pesam muito; tecnologia, quase nada.",
      "Por que importa hoje: diversificar entre ações brasileiras diversifica empresas, mas não setores nem país. Comparar o Ibovespa com o S&P 500 mostra que as duas bolsas se completam mais do que competem.",
    ],
    verbetes: ["ibovespa", "home-bias", "diversificacao"],
    antecedentes: ["1957-nasce-o-sp-500"],
    noCurso: { modulo: 0, aula: 1, tempo: "13:04" },
    fonte: "B3",
  },
  {
    slug: "1969-indices-globais",
    ano: 1969,
    categoria: "Investimentos",
    titulo: "O mundo inteiro numa régua",
    resumo: "A Capital International passa a calcular índices de bolsas do mundo todo. Depois, ganhariam o nome MSCI.",
    texto: [
      "Até então, quem quisesse comparar mercados de países diferentes tinha de juntar os dados na mão. Os índices globais da Capital International, calculados desde 1969, criaram uma régua comum. Em 1986, com a parceria do Morgan Stanley, viraram os índices MSCI.",
      "Foi com esses índices que se mediu, décadas depois, o tamanho do viés doméstico: no mundo todo, o investidor guarda em casa muito mais do que o peso do seu país.",
      "Por que importa hoje: no índice global de ações MSCI ACWI, o Brasil é menos de 0,5%. Saber disso muda a pergunta de quanto pôr lá fora para quanto deixar aqui.",
    ],
    verbetes: ["home-bias", "diversificacao", "gestao-passiva"],
    antecedentes: ["1952-markowitz-e-a-diversificacao", "1957-nasce-o-sp-500"],
    noCurso: { modulo: 0, aula: 1, tempo: "6:50" },
    fonte: "MSCI",
  },
  {
    slug: "1969-arpanet",
    ano: 1969,
    data: "29 de outubro de 1969",
    categoria: "Tecnologia e internet",
    titulo: "A primeira mensagem da rede",
    resumo: "Um computador da UCLA manda a primeira mensagem para outro, em Stanford. A Arpanet, avó da internet, começa a funcionar.",
    texto: [
      "A mensagem devia ser LOGIN. O sistema caiu depois das duas primeiras letras, e o que chegou foi LO. Mesmo assim, estava provado que computadores distantes podiam conversar quebrando a informação em pacotes.",
      "O projeto era financiado pela agência de pesquisa do Departamento de Defesa americano.",
      "Por que importa hoje: sem rede, não haveria corretora no celular, conta global aberta em minutos nem bitcoin. Tudo o que tornou o investimento internacional acessível ao pequeno investidor passa por esse fio.",
    ],
    verbetes: ["internet"],
    antecedentes: ["1958-circuito-integrado"],
    fonte: "UCLA; Computer History Museum",
  },
  {
    slug: "1971-fim-do-padrao-dolar-ouro",
    ano: 1971,
    data: "15 de agosto de 1971",
    categoria: "Dinheiro e dólar",
    titulo: "Nixon fecha a janela do ouro",
    resumo: "Os Estados Unidos deixam de trocar dólares por ouro. A partir daí, a moeda vale pela confiança em quem a emite.",
    texto: [
      "Num domingo à noite, Richard Nixon anunciou na televisão o fim da conversibilidade do dólar em ouro para outros governos, junto com congelamento de preços e uma sobretaxa de importação. O defeito apontado por Triffin tinha chegado ao limite.",
      "Em 1973, as grandes moedas passaram a flutuar umas contra as outras. Desde então, nenhuma moeda relevante tem lastro em metal: vale pela credibilidade do banco central e do governo.",
      "Por que importa hoje: num mundo de moedas sem lastro, a escolha da moeda em que você guarda patrimônio é uma escolha de instituição. É essa comparação, e não uma aposta contra o real, que está no centro do curso.",
    ],
    verbetes: ["bretton-woods", "padrao-ouro", "cambio", "banco-central"],
    antecedentes: ["1944-bretton-woods", "1960-dilema-de-triffin"],
    fonte: "Federal Reserve History",
  },
  {
    slug: "1971-microprocessador",
    ano: 1971,
    data: "15 de novembro de 1971",
    categoria: "Tecnologia e internet",
    titulo: "Um computador num chip",
    resumo: "A Intel lança o 4004, o primeiro microprocessador comercial, com 2.300 transistores.",
    texto: [
      "Pela primeira vez, toda a unidade de processamento de um computador cabia num único chip. Ele foi feito para uma calculadora japonesa, mas abriu caminho para o computador pessoal.",
      "Os processadores de hoje têm dezenas de bilhões de transistores. A curva que começou ali transformou a tecnologia no maior setor da bolsa americana.",
      "Por que importa hoje: setores inteiros que movem o mercado global simplesmente não existem na bolsa brasileira. É uma das razões, mais do que juros, para olhar para fora.",
    ],
    verbetes: ["internet", "sp-500"],
    antecedentes: ["1958-circuito-integrado"],
    fonte: "Intel; Computer History Museum",
  },
  {
    slug: "1973-choque-do-petroleo",
    ano: 1973,
    data: "outubro de 1973",
    categoria: "Crises",
    titulo: "O primeiro choque do petróleo",
    resumo: "Os países árabes exportadores cortam a produção e embargam os Estados Unidos. O preço do barril quadruplica em poucos meses.",
    texto: [
      "Em resposta à guerra do Yom Kippur, os produtores árabes reduziram a oferta e suspenderam vendas aos Estados Unidos. O barril, perto de US$ 3, passou de US$ 12 no começo de 1974. O mundo rico entrou em recessão com inflação, a estagflação.",
      "O Brasil, que importava a maior parte do petróleo que consumia, escolheu seguir crescendo com dívida externa em dólar. A conta chegaria na década seguinte.",
      "Por que importa hoje: choques de fora atingem câmbio, inflação e juros ao mesmo tempo. Ter parte do patrimônio em outra moeda não evita o choque, mas muda quem paga por ele.",
    ],
    verbetes: ["inflacao", "divida-publica", "risco-cambial"],
    antecedentes: ["1971-fim-do-padrao-dolar-ouro"],
    fonte: "Federal Reserve History, Oil Shock of 1973-74",
  },
  {
    slug: "1975-fim-da-corretagem-fixa",
    ano: 1975,
    data: "1º de maio de 1975",
    categoria: "Investimentos",
    titulo: "O dia em que a corretagem ficou livre",
    resumo: "A SEC acaba com as comissões fixas da Bolsa de Nova York. Começa a corrida para baratear o investimento.",
    texto: [
      "Desde o acordo de 1792, os corretores cobravam uma tabela mínima. Em 1975, a SEC obrigou o mercado a competir no preço. Corretoras de desconto, como a Charles Schwab, cresceram nesse vácuo.",
      "O mesmo movimento, décadas depois, levaria à corretagem zero nos aplicativos.",
      "Por que importa hoje: custo come retorno de forma silenciosa. A tendência de longo prazo de baratear o acesso é parte do que tornou viável investir lá fora com valores pequenos, mas ainda vale comparar taxas, câmbio e impostos.",
    ],
    verbetes: ["etf", "gestao-passiva"],
    antecedentes: ["1934-nasce-a-sec", "1792-acordo-de-buttonwood"],
    fonte: "SEC",
  },
  {
    slug: "1976-primeiro-fundo-de-indice",
    ano: 1976,
    data: "31 de agosto de 1976",
    categoria: "Investimentos",
    titulo: "O primeiro fundo de índice para o varejo",
    resumo: "John Bogle, da Vanguard, lança um fundo que só copia o S&P 500. Foi chamado de loucura.",
    texto: [
      "A ideia era desistir de bater o mercado e simplesmente ser o mercado, com custo baixo. A captação inicial foi de US$ 11,3 milhões, bem abaixo do esperado, e o fundo ganhou o apelido de loucura do Bogle.",
      "Meio século depois, os fundos de índice e os ETFs passivos administram trilhões de dólares e mudaram a forma como o mundo investe.",
      "Por que importa hoje: com um único fundo de índice, você compra centenas de empresas de outro país. Para quem está começando a dolarizar, a gestão passiva resolve a diversificação antes da escolha de ações.",
    ],
    verbetes: ["gestao-passiva", "gestao-passiva", "sp-500"],
    antecedentes: ["1957-nasce-o-sp-500", "1952-markowitz-e-a-diversificacao"],
    fonte: "Vanguard",
  },
  {
    slug: "1979-choque-volcker",
    ano: 1979,
    data: "6 de outubro de 1979",
    categoria: "Dinheiro e dólar",
    titulo: "O choque Volcker",
    resumo: "O Fed de Paul Volcker muda a forma de conduzir a política monetária e leva os juros americanos para perto de 20% para vencer a inflação.",
    texto: [
      "O segundo choque do petróleo, com a Revolução Iraniana, empurrou a inflação americana para perto de 15% ao ano. Volcker, recém-empossado, decidiu que o Fed faria o que fosse preciso. Os juros chegaram a 20% em 1981, e os Estados Unidos aguentaram duas recessões.",
      "A inflação caiu, e o dólar e o Fed ganharam uma credibilidade que dura até hoje. Do lado de cá, a América Latina, endividada em dólar a juros flutuantes, quebrou.",
      "Por que importa hoje: a credibilidade de um banco central se constrói pagando o custo de cumprir a promessa. Essa história explica por que o mercado confia mais no dólar e por que juro americano alto costuma pressionar países como o Brasil.",
    ],
    verbetes: ["banco-central", "inflacao", "juro-real", "treasury"],
    antecedentes: ["1971-fim-do-padrao-dolar-ouro", "1973-choque-do-petroleo"],
    noCurso: { modulo: 0, aula: 2, tempo: "4:02" },
    fonte: "Federal Reserve History",
  },
  {
    slug: "1982-crise-da-divida-latino-americana",
    ano: 1982,
    data: "agosto de 1982",
    categoria: "Crises",
    titulo: "O México para de pagar",
    resumo: "O México avisa que não consegue honrar a dívida externa. Começa a década perdida da América Latina.",
    texto: [
      "Com os juros americanos nas alturas, as dívidas em dólar tomadas nos anos 1970 ficaram impagáveis. O México foi o primeiro a avisar. O crédito para a região secou, e o Brasil recorreu ao FMI ainda em 1982.",
      "Cinco anos depois, seria a vez do Brasil decretar moratória. A renegociação só terminaria em 1994.",
      "Por que importa hoje: países que dependem de dinheiro de fora sentem primeiro quando o Fed aperta. Dívida em moeda que o país não emite é a combinação que mais derrubou emergentes.",
    ],
    verbetes: ["divida-publica", "risco-pais", "cambio"],
    antecedentes: ["1979-choque-volcker"],
    noCurso: { modulo: 0, aula: 2, tempo: "4:02" },
    fonte: "Federal Reserve History, Latin American Debt Crisis of the 1980s",
  },
  {
    slug: "1983-tcp-ip",
    ano: 1983,
    data: "1º de janeiro de 1983",
    categoria: "Tecnologia e internet",
    titulo: "A internet ganha uma língua comum",
    resumo: "A Arpanet adota o TCP/IP, o protocolo de Vint Cerf e Bob Kahn que permite a redes diferentes conversarem entre si.",
    texto: [
      "O protocolo tinha sido descrito em 1974. Na virada de 1983, todas as máquinas da Arpanet passaram a usá-lo de uma vez. É por isso que muita gente considera essa a data de nascimento da internet.",
      "Com uma língua comum, qualquer rede podia se ligar a qualquer outra, sem dono central.",
      "Por que importa hoje: a mesma ideia de padrão aberto sustenta o mercado digital de hoje, das ordens de compra transmitidas em milissegundos às redes cripto. O investidor pequeno chega ao mundo por essa porta.",
    ],
    verbetes: ["internet"],
    antecedentes: ["1969-arpanet"],
    fonte: "Internet Society",
  },
  {
    slug: "1985-acordo-do-plaza",
    ano: 1985,
    data: "22 de setembro de 1985",
    categoria: "Dinheiro e dólar",
    titulo: "O acordo do Plaza",
    resumo: "Os cinco países mais ricos combinam derrubar o dólar, que tinha subido demais depois do choque de juros.",
    texto: [
      "Com juros altos, o dólar tinha se valorizado muito e a indústria americana perdia competitividade. Estados Unidos, Japão, Alemanha Ocidental, França e Reino Unido se reuniram no Hotel Plaza, em Nova York, e combinaram vender dólares. Nos anos seguintes, o dólar perdeu boa parte do valor contra o iene e o marco.",
      "O dólar forte de uma década virou o dólar fraco da seguinte.",
      "Por que importa hoje: o dólar também oscila, às vezes por anos. Quem dolariza carrega risco cambial dos dois lados, e por isso o curso fala em parte do patrimônio e em aportes ao longo do tempo, não em acertar o momento.",
    ],
    verbetes: ["cambio", "risco-cambial", "market-timing"],
    antecedentes: ["1979-choque-volcker"],
    fonte: "Federal Reserve History; Departamento do Tesouro dos EUA",
  },
  {
    slug: "1986-plano-cruzado",
    ano: 1986,
    data: "28 de fevereiro de 1986",
    categoria: "Brasil",
    titulo: "Plano Cruzado",
    resumo: "O governo Sarney corta três zeros, cria o cruzado e congela preços. A inflação cai por meses e volta mais forte.",
    texto: [
      "O plano foi recebido com euforia: consumidores viraram fiscais do Sarney, conferindo a tabela de preços nos supermercados. A inflação caiu a um terço em 1986. Só que, com preços congelados e demanda aquecida, sumiram produtos das prateleiras e o ágio se espalhou.",
      "Depois das eleições de novembro, o congelamento ruiu. Em 1987, a inflação explodiu.",
      "Por que importa hoje: trocar o nome da moeda e congelar preços não cria confiança em quem emite o dinheiro. É a lição que separa os planos fracassados do Plano Real.",
    ],
    verbetes: ["hiperinflacao", "inflacao", "imposto-inflacionario"],
    antecedentes: ["1964-nasce-o-banco-central", "1982-crise-da-divida-latino-americana"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:57" },
    fonte: "Decreto-Lei 2.283/1986; BCB, Museu de Valores",
  },
  {
    slug: "1987-moratoria-e-plano-bresser",
    ano: 1987,
    data: "20 de fevereiro e 12 de junho de 1987",
    categoria: "Brasil",
    titulo: "Moratória e Plano Bresser",
    resumo: "Em fevereiro, o Brasil suspende o pagamento de juros da dívida externa. Em junho, vem outro congelamento de preços.",
    texto: [
      "Sem dólares para pagar, o governo declarou moratória da dívida com os bancos estrangeiros. Meses depois, o ministro Luiz Carlos Bresser-Pereira tentou de novo: congelamento de 90 dias e reajustes de tarifas.",
      "A inflação voltou logo em seguida. E a moratória deixou o Brasil anos fora do mercado de crédito internacional.",
      "Por que importa hoje: calote e renegociação forçada são uma das portas por onde um governo fecha a conta, e quem paga é o credor. Quem concentra tudo em ativos de um só país está do lado de quem paga.",
    ],
    verbetes: ["divida-publica", "risco-pais", "hiperinflacao"],
    antecedentes: ["1986-plano-cruzado", "1982-crise-da-divida-latino-americana"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:57" },
    fonte: "Banco Central do Brasil; Decreto-Lei 2.335/1987",
  },
  {
    slug: "1987-segunda-feira-negra",
    ano: 1987,
    data: "19 de outubro de 1987",
    categoria: "Crises",
    titulo: "A segunda-feira negra",
    resumo: "O índice Dow Jones cai 22,6% num único dia, a maior queda diária da sua história.",
    texto: [
      "Não houve guerra nem quebra de banco. Programas automáticos de venda, ações caras e pânico se alimentaram uns aos outros. No dia seguinte, o Fed, já sob Alan Greenspan, avisou que daria liquidez ao sistema, e o mercado se acalmou.",
      "Quem vendeu no pânico realizou a perda. Quem ficou viu a bolsa recuperar o nível anterior em cerca de dois anos.",
      "Por que importa hoje: os piores dias costumam vir colados aos melhores. Sair na queda para esperar passar é o comportamento que mais custa ao investidor, aqui ou lá fora.",
    ],
    verbetes: ["volatilidade", "market-timing"],
    antecedentes: ["1929-crash-de-nova-york"],
    noCurso: { modulo: 0, aula: 3, tempo: "6:57" },
    fonte: "Federal Reserve History, Stock Market Crash of 1987",
  },
  {
    slug: "1989-plano-verao",
    ano: 1989,
    data: "15 de janeiro de 1989",
    categoria: "Brasil",
    titulo: "Plano Verão",
    resumo: "Mais três zeros cortados, nasce o cruzado novo e vem outro congelamento de preços.",
    texto: [
      "Sob o ministro Maílson da Nóbrega, a medida provisória criou o cruzado novo, que valia mil cruzados, congelou preços e tentou desindexar a economia. Foi o terceiro plano em três anos.",
      "A inflação voltou em poucos meses. No fim de 1989, os preços subiam mais de 50% ao mês, e o país entrava na hiperinflação aberta.",
      "Por que importa hoje: cada plano fracassado ensinava as pessoas a se defender mais cedo, com overnight, dólar e indexação. O hábito brasileiro de procurar proteção vem dessa época.",
    ],
    verbetes: ["hiperinflacao", "inflacao"],
    antecedentes: ["1987-moratoria-e-plano-bresser"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:57" },
    fonte: "Medida Provisória 32/1989 (Lei 7.730/1989)",
  },
  {
    slug: "1990-plano-collor",
    ano: 1990,
    data: "16 de março de 1990",
    categoria: "Brasil",
    titulo: "Plano Collor e o bloqueio",
    resumo: "No dia seguinte à posse, o governo bloqueia o dinheiro acima de NCz$ 50 mil em contas e aplicações. Volta o cruzeiro.",
    texto: [
      "A ministra Zélia Cardoso de Mello anunciou o plano numa sexta-feira. Contas correntes, poupança e aplicações acima do limite ficaram retidas no Banco Central por 18 meses e só começaram a voltar em 12 parcelas, a partir de setembro de 1991. Em março de 1990, o IPCA tinha subido 82% num único mês.",
      "A inflação caiu por pouco tempo e voltou. O que ficou foi a memória de que o governo pode, de uma vez, travar o dinheiro de todo mundo.",
      "Por que importa hoje: trocar uma aplicação brasileira por outra não protege contra uma decisão desse tipo, porque todas estão sob a mesma caneta. Só outra jurisdição dilui esse risco.",
    ],
    verbetes: ["plano-collor", "hiperinflacao", "divida-publica"],
    antecedentes: ["1989-plano-verao"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:57" },
    fonte: "Medida Provisória 168/1990 (Lei 8.024/1990)",
  },
  {
    slug: "1991-world-wide-web",
    ano: 1991,
    data: "6 de agosto de 1991",
    categoria: "Tecnologia e internet",
    titulo: "A web",
    resumo: "Tim Berners-Lee, do CERN, torna público o projeto World Wide Web: páginas com links, abertas a qualquer um.",
    texto: [
      "A internet já existia, mas era coisa de universidade e governo. Berners-Lee juntou páginas, endereços e links num sistema simples. Em abril de 1993, o CERN liberou a tecnologia em domínio público, sem cobrar royalties.",
      "Foi a decisão que permitiu a explosão de sites, comércio eletrônico e, depois, corretoras on-line.",
      "Por que importa hoje: informação de mercado que antes era privilégio de poucos virou pública e gratuita. Isso nivela o acesso, mas também aumenta o ruído, e o curso insiste em método, não em manchete.",
    ],
    verbetes: ["internet"],
    antecedentes: ["1983-tcp-ip"],
    fonte: "CERN",
  },
  {
    slug: "1993-primeiro-etf",
    ano: 1993,
    data: "22 de janeiro de 1993",
    categoria: "Investimentos",
    titulo: "O primeiro ETF americano",
    resumo: "Nasce o SPDR S&P 500, o SPY: um fundo de índice negociado na bolsa como se fosse uma ação.",
    texto: [
      "O fundo começou a operar com US$ 6,5 milhões e as cotas passaram a ser negociadas na bolsa americana uma semana depois. A ideia juntava o fundo de índice de Bogle com a praticidade de comprar e vender durante o pregão.",
      "O interesse inicial foi baixo. Três décadas depois, o SPY é um dos maiores fundos do mundo, e os ETFs viraram o veículo padrão para investir em índices.",
      "Por que importa hoje: é o ETF que permite comprar centenas de empresas de outro país numa única ordem, com custo baixo. Os detalhes de domicílio, imposto e custo ficam para o Módulo III.",
    ],
    verbetes: ["etf", "gestao-passiva", "sp-500", "gestao-passiva"],
    antecedentes: ["1976-primeiro-fundo-de-indice", "1957-nasce-o-sp-500"],
    fonte: "State Street Global Advisors",
  },
  {
    slug: "1993-manifesto-cypherpunk",
    ano: 1993,
    data: "9 de março de 1993",
    categoria: "Cripto",
    titulo: "Os cypherpunks",
    resumo: "Eric Hughes publica o Manifesto Cypherpunk: privacidade é necessária numa sociedade aberta na era eletrônica.",
    texto: [
      "A matemática já existia desde 1976, quando Whitfield Diffie e Martin Hellman mostraram como duas pessoas podem trocar segredos por um canal aberto. Os cypherpunks transformaram a criptografia em causa: proteger a privacidade com código, e não com promessas de governos ou empresas.",
      "Desse grupo saíram várias tentativas de dinheiro digital ao longo dos anos 1990. Nenhuma pegou, mas as peças foram ficando prontas.",
      "Por que importa hoje: o bitcoin não caiu do céu em 2008. Entender sua origem ajuda a separar a tecnologia do discurso, tema do Módulo IV.",
    ],
    verbetes: ["bitcoin", "blockchain"],
    antecedentes: ["1983-tcp-ip"],
    fonte: "E. Hughes, A Cypherpunk's Manifesto; W. Diffie e M. Hellman, New Directions in Cryptography",
  },
  {
    slug: "1994-urv",
    ano: 1994,
    data: "1º de março de 1994",
    categoria: "Brasil",
    titulo: "A URV",
    resumo: "Preços, salários e contratos passam a ser escritos numa unidade estável enquanto o pagamento continua em cruzeiros reais.",
    texto: [
      "Depois do cruzeiro real, de agosto de 1993, a equipe de Fernando Henrique Cardoso no Ministério da Fazenda fez algo diferente: em vez de congelar, criou uma régua. A Unidade Real de Valor era corrigida todo dia e valia quase um dólar. Por quatro meses, as pessoas se acostumaram a pensar em URV.",
      "Em abril, o Brasil fechou o acordo da dívida externa com os bancos, sem o FMI. Era o fim de uma pendência que vinha de 1987.",
      "Por que importa hoje: a URV separou as funções da moeda, régua, meio de pagamento e reserva de valor. É o mesmo raciocínio que o curso usa para pensar em qual moeda você guarda patrimônio.",
    ],
    verbetes: ["urv", "plano-real", "hiperinflacao"],
    antecedentes: ["1990-plano-collor", "1986-plano-cruzado"],
    noCurso: { modulo: 0, aula: 2, tempo: "9:02" },
    fonte: "Medida Provisória 434/1994 (Lei 8.880/1994); BCB",
  },
  {
    slug: "1994-plano-real",
    ano: 1994,
    data: "1º de julho de 1994",
    categoria: "Brasil",
    titulo: "Nasce o real",
    resumo: "Cada URV vira um real, e CR$ 2.750 passam a valer R$ 1. A hiperinflação acaba.",
    texto: [
      "Em 1993, a inflação tinha passado de 2.400% no ano. Em 1995, já estava em 22%. O real nasceu preso ao dólar, com o Banco Central controlando o câmbio, e com juros altos para atrair dólares.",
      "Sem a inflação, o governo perdeu o imposto inflacionário, uma receita que não precisava passar pelo Congresso, e o rombo das contas apareceu. A âncora do câmbio comprou tempo para arrumar o resto.",
      "Por que importa hoje: o real é a moeda mais bem-sucedida do Brasil em um século, e mesmo assim passou por vários choques. Valorizar o que o real conquistou e diversificar parte do patrimônio não se contradizem.",
    ],
    verbetes: ["plano-real", "urv", "imposto-inflacionario", "cambio"],
    antecedentes: ["1994-urv", "1942-nasce-o-cruzeiro"],
    noCurso: { modulo: 0, aula: 2, tempo: "12:06" },
    fonte: "Lei 8.880/1994; BCB; IBGE, IPCA",
  },
  {
    slug: "1994-crise-do-mexico",
    ano: 1994,
    data: "20 de dezembro de 1994",
    categoria: "Crises",
    titulo: "A crise do México",
    resumo: "O México desvaloriza o peso, que despenca. O efeito tequila contamina os emergentes.",
    texto: [
      "Com o Fed subindo juros ao longo de 1994 e uma crise política interna, os dólares fugiram do México. O governo alargou a banda do câmbio e, dias depois, deixou o peso flutuar. Os Estados Unidos e o FMI montaram um socorro de cerca de US$ 50 bilhões.",
      "O Brasil, com o real recém-nascido e preso ao dólar, sentiu o golpe e precisou de juros ainda mais altos.",
      "Por que importa hoje: crises de um emergente costumam respingar nos outros, porque o investidor global vende o pacote inteiro. O real responde também a eventos que não têm nada a ver com o Brasil.",
    ],
    verbetes: ["risco-pais", "cambio", "embi"],
    antecedentes: ["1982-crise-da-divida-latino-americana", "1994-plano-real"],
    noCurso: { modulo: 0, aula: 2, tempo: "21:18" },
    fonte: "Federal Reserve History; FMI",
  },
  {
    slug: "1995-ipo-da-netscape",
    ano: 1995,
    data: "9 de agosto de 1995",
    categoria: "Tecnologia e internet",
    titulo: "A estreia da Netscape",
    resumo: "A dona do navegador mais usado da época abre o capital. A ação, vendida a US$ 28, fecha o primeiro dia a US$ 58,25.",
    texto: [
      "A Netscape quase não dava lucro, mas tinha o programa pelo qual milhões de pessoas entravam na web. A estreia na bolsa virou símbolo de uma nova era: a internet tinha virado negócio.",
      "Foi o tiro de largada da corrida às ações de internet, que terminaria cinco anos depois numa bolha.",
      "Por que importa hoje: tecnologias transformadoras e bons investimentos nem sempre coincidem. Preço pago importa, e a diversificação protege de apostar tudo na empresa errada da revolução certa.",
    ],
    verbetes: ["internet", "volatilidade"],
    antecedentes: ["1991-world-wide-web"],
    fonte: "Computer History Museum; registros da Nasdaq",
  },
  {
    slug: "1997-deep-blue",
    ano: 1997,
    data: "11 de maio de 1997",
    categoria: "Inteligência artificial",
    titulo: "Deep Blue vence Kasparov",
    resumo: "O computador da IBM derrota o campeão mundial de xadrez numa série de seis partidas.",
    texto: [
      "Garry Kasparov tinha vencido a máquina no ano anterior. Na revanche, em Nova York, o Deep Blue ganhou por 3,5 a 2,5. Não era uma máquina que aprendia: era força bruta, calculando milhões de posições por segundo.",
      "O impacto simbólico foi enorme: uma atividade vista como o auge do intelecto humano tinha sido dominada por um computador.",
      "Por que importa hoje: a capacidade de computação é o combustível de toda a inteligência artificial. As empresas que vendem essa capacidade estão entre as maiores do índice americano.",
    ],
    verbetes: ["inteligencia-artificial"],
    antecedentes: ["1956-conferencia-de-dartmouth", "1971-microprocessador"],
    fonte: "IBM",
  },
  {
    slug: "1997-crise-asiatica",
    ano: 1997,
    data: "2 de julho de 1997",
    categoria: "Crises",
    titulo: "A crise asiática",
    resumo: "A Tailândia solta o baht. A crise se espalha por Indonésia, Coreia do Sul e outros vizinhos.",
    texto: [
      "Os tigres asiáticos cresciam rápido com dinheiro de fora e moedas presas ao dólar. Quando o baht cedeu, o mercado testou as moedas vizinhas uma a uma. O FMI montou pacotes para Tailândia, Indonésia e Coreia do Sul.",
      "O Brasil, também com câmbio controlado, subiu os juros para segurar os dólares. A desconfiança com moedas emergentes atreladas ao dólar não ia passar.",
      "Por que importa hoje: câmbio fixo sem contas em ordem é uma promessa que o mercado testa. Quando ela quebra, quebra de uma vez, e quem está todo na moeda local sente no patrimônio.",
    ],
    verbetes: ["cambio", "risco-pais", "risco-cambial"],
    antecedentes: ["1994-crise-do-mexico"],
    fonte: "FMI; Federal Reserve History",
  },
  {
    slug: "1998-moratoria-russa",
    ano: 1998,
    data: "17 de agosto de 1998",
    categoria: "Crises",
    titulo: "A moratória russa",
    resumo: "A Rússia desvaloriza o rublo e deixa de pagar parte da dívida. Um grande fundo americano quase quebra junto.",
    texto: [
      "O calote russo pegou o mercado de surpresa e derrubou o LTCM, um fundo americano cheio de prêmios Nobel e alavancagem. Em setembro, o Fed de Nova York coordenou um resgate com bancos privados.",
      "Para o Brasil, foi a gota d'água: os dólares saíram em massa e o país fechou um acordo com o FMI no fim do ano. O câmbio controlado tinha os dias contados.",
      "Por que importa hoje: crises fazem ativos que pareciam não ter relação caírem juntos, e a liquidez some na hora em que mais se precisa dela.",
    ],
    verbetes: ["risco-pais", "embi", "volatilidade"],
    antecedentes: ["1997-crise-asiatica"],
    noCurso: { modulo: 0, aula: 2, tempo: "21:18" },
    fonte: "Federal Reserve History; FMI",
  },
  {
    slug: "1999-nasce-o-euro",
    ano: 1999,
    data: "1º de janeiro de 1999",
    categoria: "Dinheiro e dólar",
    titulo: "Nasce o euro",
    resumo: "Onze países europeus passam a ter uma moeda única, com um banco central comum. As cédulas chegam em 2002.",
    texto: [
      "Foi o maior experimento monetário desde Bretton Woods: países com histórias, impostos e dívidas diferentes abriram mão da própria moeda. O euro nasceu como a segunda moeda de reserva do mundo.",
      "Desde então, ganhou espaço, mas nunca chegou perto do dólar. A crise de 2010 mostraria o custo de ter moeda comum sem orçamento comum.",
      "Por que importa hoje: dolarizar não quer dizer só Estados Unidos. Euro, iene e outras moedas também diversificam, mas cada uma tem o seu risco, e o dólar segue no centro do sistema.",
    ],
    verbetes: ["cambio", "banco-central", "diversificacao"],
    antecedentes: ["1971-fim-do-padrao-dolar-ouro", "1985-acordo-do-plaza"],
    fonte: "Banco Central Europeu",
  },
  {
    slug: "1999-cambio-flutuante",
    ano: 1999,
    data: "15 de janeiro de 1999",
    categoria: "Brasil",
    titulo: "O real passa a flutuar",
    resumo: "Depois da moratória de Minas Gerais e da saída de Gustavo Franco do Banco Central, o câmbio é liberado.",
    texto: [
      "Em 6 de janeiro, o governador Itamar Franco anunciou a moratória da dívida de Minas com a União. A desconfiança se espalhou, Franco deixou o Banco Central no dia 13 e, no dia 15, o real passou a flutuar. Pela cotação oficial, o dólar foi de R$ 1,21 em 12 de janeiro para R$ 1,98 no dia 29.",
      "Diferente da Argentina, três anos depois, o Brasil saiu do câmbio fixo trocando de regime, sem calote.",
      "Por que importa hoje: uma briga entre dois pedaços do mesmo Estado redesenhou em semanas o patrimônio de quem tinha tudo em reais. O câmbio flutuante é o regime até hoje, e com ele o real passou a absorver os choques.",
    ],
    verbetes: ["cambio", "risco-cambial", "tripe-macroeconomico"],
    antecedentes: ["1994-plano-real", "1998-moratoria-russa"],
    noCurso: { modulo: 0, aula: 2, tempo: "24:50" },
    fonte: "Banco Central do Brasil, PTAX (SGS 1)",
  },
  {
    slug: "1999-metas-de-inflacao",
    ano: 1999,
    data: "21 de junho de 1999",
    categoria: "Brasil",
    titulo: "Metas de inflação e o tripé",
    resumo: "Um decreto cria o regime de metas de inflação. Com o superávit primário e o câmbio flutuante, forma o tripé.",
    texto: [
      "Arminio Fraga assumiu o Banco Central em março e montou o regime em poucos meses: o governo define um alvo de inflação e o Banco Central calibra os juros para chegar lá. Junto vieram metas de superávit nas contas públicas.",
      "Com ajustes, é o regime que o Brasil usa até hoje. Desde 2025, o alvo é de 3%, cobrado continuamente.",
      "Por que importa hoje: a credibilidade do tripé é o que segura o real e os juros longos. Quando o mercado duvida dela, o dólar e o prêmio de risco sobem antes da inflação.",
    ],
    verbetes: ["meta-de-inflacao", "tripe-macroeconomico", "selic", "banco-central"],
    antecedentes: ["1999-cambio-flutuante"],
    noCurso: { modulo: 0, aula: 2, tempo: "31:42" },
    fonte: "Decreto 3.088/1999; Banco Central do Brasil",
  },
  {
    slug: "2000-bolha-pontocom",
    ano: 2000,
    data: "10 de março de 2000",
    categoria: "Crises",
    titulo: "O estouro da bolha pontocom",
    resumo: "A Nasdaq atinge o pico de 5.048 pontos. Em dois anos e meio, perderia cerca de 78%.",
    texto: [
      "Empresas sem lucro valiam bilhões só por terem ponto com no nome. Quando o dinheiro barato acabou e os resultados não vieram, as ações despencaram. A Nasdaq só voltou ao pico de 2000 em 2015.",
      "Muitas empresas sumiram. Algumas sobreviveram e viraram gigantes da década seguinte.",
      "Por que importa hoje: até o mercado americano passa por bolhas setoriais. Quem estava concentrado em tecnologia em 2000 levou mais de uma década para recuperar. Diversificar vale também dentro de lá.",
    ],
    verbetes: ["volatilidade", "diversificacao", "market-timing"],
    antecedentes: ["1995-ipo-da-netscape", "1987-segunda-feira-negra"],
    fonte: "Nasdaq",
  },
  {
    slug: "2000-lei-de-responsabilidade-fiscal",
    ano: 2000,
    data: "4 de maio de 2000",
    categoria: "Brasil",
    titulo: "Lei de Responsabilidade Fiscal",
    resumo: "A lei limita gastos com pessoal e endividamento e proíbe o governo de se financiar nos próprios bancos.",
    texto: [
      "A União tinha renegociado as dívidas de estados e municípios várias vezes, e cada socorro virava dívida federal. A LRF pôs limites e punições, e seus artigos 35 e 36 proíbem que um ente se financie no banco que controla.",
      "Foi o desrespeito a essa lógica, com bancos públicos cobrindo despesas da União, que embasou o impeachment de 2016.",
      "Por que importa hoje: regra fiscal crível é o que reduz o prêmio que o mercado cobra do Brasil. Quando as regras são contornadas, o investidor paga no câmbio e nos juros.",
    ],
    verbetes: ["divida-publica", "tripe-macroeconomico", "risco-pais"],
    antecedentes: ["1999-metas-de-inflacao", "1999-cambio-flutuante"],
    noCurso: { modulo: 0, aula: 2, tempo: "31:42" },
    fonte: "Lei Complementar 101/2000",
  },
  {
    slug: "2001-corralito-argentino",
    ano: 2001,
    data: "1º de dezembro de 2001",
    categoria: "Crises",
    titulo: "O corralito argentino",
    resumo: "A Argentina limita os saques bancários. Semanas depois, declara o maior calote de dívida externa até então e abandona a paridade com o dólar.",
    texto: [
      "Desde 1991, uma lei garantia um peso por um dólar. Sem ajuste nas contas, a promessa ficou insustentável. O governo travou os saques, o presidente renunciou e, em janeiro de 2002, a paridade acabou. Depósitos em dólar foram convertidos à força em pesos.",
      "Quem achava que tinha dólares no banco descobriu que tinha uma promessa local de dólares.",
      "Por que importa hoje: dólar dentro do sistema de um país continua sujeito às regras desse país. É a diferença entre ter um ativo em dólar e ter um ativo fora do alcance de uma única caneta.",
    ],
    verbetes: ["risco-pais", "divida-publica", "cambio"],
    antecedentes: ["1998-moratoria-russa", "1999-cambio-flutuante"],
    noCurso: { modulo: 0, aula: 2, tempo: "13:06" },
    fonte: "Argentina, Decreto 1.570/2001 e Lei 25.561/2002",
  },
  {
    slug: "2001-china-na-omc",
    ano: 2001,
    data: "11 de dezembro de 2001",
    categoria: "Brasil",
    titulo: "A China entra na OMC, e o Brasil pega carona",
    resumo: "A China passa a fazer parte da Organização Mundial do Comércio e começa a década que dispara o preço das commodities.",
    texto: [
      "Centenas de milhões de chineses foram do campo para as cidades, e isso virou demanda por minério, soja, carne e petróleo, justamente o que o Brasil vende. Em dólar, o índice de commodities do Banco Central quase triplicou entre 2002 e 2011.",
      "Com o vento a favor, a dívida caiu, os juros recuaram e o dólar chegou a R$ 1,53 em julho de 2011.",
      "Por que importa hoje: boa parte da bolsa e do câmbio brasileiros depende do ciclo das commodities, que o Brasil não controla. Quem comprou dólar em 2002 e deixou parado até 2010 perdeu poder de compra; quem comprou em 2011 viveu o contrário.",
    ],
    verbetes: ["cambio", "ibovespa", "pib"],
    antecedentes: ["2000-lei-de-responsabilidade-fiscal"],
    noCurso: { modulo: 0, aula: 2, tempo: "47:14" },
    fonte: "OMC; Banco Central do Brasil, IC-Br (SGS 29042)",
  },
  {
    slug: "2002-crise-de-confianca",
    ano: 2002,
    data: "22 de outubro de 2002",
    categoria: "Crises",
    titulo: "2002: o preço da incerteza",
    resumo: "Às vésperas da eleição, o dólar chega a R$ 3,96 e o risco-país passa de 2.400 pontos.",
    texto: [
      "O favorito, Lula, tinha se oposto ao Plano Real, à LRF e ao tripé. O mercado cobrou pela hipótese de ruptura antes de qualquer ato: o dólar subiu 74% entre abril e outubro, e o risco-país chegou a 2.443 pontos em 27 de setembro. Em junho, a Carta ao Povo Brasileiro prometeu respeitar contratos e superávit; em agosto, o país fechou acordo com o FMI.",
      "O governo eleito cumpriu a carta, e o prêmio caiu sem que a dívida tivesse mudado de tamanho.",
      "Por que importa hoje: o risco político aparece no câmbio e nos juros antes de aparecer nos fatos. Eleições no Brasil costumam mexer no dólar, e o curso trata isso como risco a diluir, não a adivinhar.",
    ],
    verbetes: ["risco-pais", "embi", "cambio", "selic"],
    antecedentes: ["2000-lei-de-responsabilidade-fiscal", "2001-corralito-argentino"],
    noCurso: { modulo: 0, aula: 2, tempo: "41:25" },
    fonte: "Banco Central do Brasil (SGS 1); JP Morgan, EMBI+, via IpeaData",
  },
  {
    slug: "2006-computacao-em-nuvem",
    ano: 2006,
    data: "14 de março de 2006",
    categoria: "Tecnologia e internet",
    titulo: "A nuvem",
    resumo: "A Amazon lança o S3, serviço de armazenamento pago por uso. Começa a computação em nuvem como a conhecemos.",
    texto: [
      "Em vez de comprar servidores, empresas passaram a alugar capacidade pela internet e pagar só pelo que usam. Meses depois veio o aluguel de processamento. Startups puderam nascer sem montar data center.",
      "A nuvem virou um dos negócios mais lucrativos do mundo e a base onde rodam hoje aplicativos, bancos digitais e modelos de inteligência artificial.",
      "Por que importa hoje: corretoras, contas globais e plataformas de investimento rodam nessa infraestrutura. E as empresas que a controlam pesam muito nos índices americanos que você compra ao dolarizar.",
    ],
    verbetes: ["internet", "sp-500"],
    antecedentes: ["1995-ipo-da-netscape"],
    fonte: "Amazon Web Services",
  },
  {
    slug: "2007-iphone",
    ano: 2007,
    data: "9 de janeiro de 2007",
    categoria: "Tecnologia e internet",
    titulo: "O iPhone",
    resumo: "Steve Jobs apresenta o iPhone. Um ano depois, a loja de aplicativos abre o celular para programas de terceiros.",
    texto: [
      "Um telefone, um tocador de música e um navegador de internet num aparelho só, com tela sensível ao toque. Em julho de 2008, a App Store transformou o celular em plataforma para qualquer serviço, inclusive financeiro.",
      "Em poucos anos, o smartphone virou o principal computador de bilhões de pessoas.",
      "Por que importa hoje: é pelo celular que você abre conta global, compra ETF e acompanha o câmbio. O aparelho que você está segurando é, ele mesmo, de uma empresa americana ou sul-coreana.",
    ],
    verbetes: ["internet", "conta-global"],
    antecedentes: ["1991-world-wide-web", "1971-microprocessador"],
    noCurso: { modulo: 0, aula: 1, tempo: "0:19" },
    fonte: "Apple",
  },
  {
    slug: "2008-grau-de-investimento",
    ano: 2008,
    data: "30 de abril de 2008",
    categoria: "Brasil",
    titulo: "O Brasil vira grau de investimento",
    resumo: "A Standard & Poor's dá ao Brasil a nota de bom pagador. Fitch e Moody's seguem depois.",
    texto: [
      "Foi o reconhecimento de uma década de tripé, LRF, superávits e dívida externa em queda. Com a nota, fundos estrangeiros que só podem comprar países bem avaliados passaram a poder investir aqui.",
      "O selo duraria sete anos.",
      "Por que importa hoje: as notas de crédito resumem o que o mercado acha da capacidade do país de pagar. Elas sobem devagar, com anos de disciplina, e caem depressa, como o Brasil veria em 2015.",
    ],
    verbetes: ["risco-pais", "divida-publica", "tripe-macroeconomico"],
    antecedentes: ["2002-crise-de-confianca", "2000-lei-de-responsabilidade-fiscal", "2001-china-na-omc"],
    fonte: "S&P Global Ratings",
  },
  {
    slug: "2008-quebra-do-lehman",
    ano: 2008,
    data: "15 de setembro de 2008",
    categoria: "Crises",
    titulo: "A quebra do Lehman Brothers",
    resumo: "O quarto maior banco de investimento americano pede falência. A crise do crédito imobiliário vira crise global.",
    texto: [
      "Os preços dos imóveis americanos caíram, as garantias passaram a valer menos que as dívidas, e os papéis lastreados nessas hipotecas contaminaram bancos do mundo inteiro. Com a quebra do Lehman, o crédito congelou. O Tesouro americano aprovou um pacote de US$ 700 bilhões em outubro.",
      "O S&P 500 caiu cerca de 57% entre o pico de 2007 e o fundo de março de 2009. Até bancos tradicionais cortaram dividendos.",
      "Por que importa hoje: em 2008, quem media o patrimônio em reais viu o dólar subir enquanto a bolsa caía, e a parte dolarizada amorteceu a queda. Não é regra, mas é o que diversificar entre moedas costuma fazer nas crises globais.",
    ],
    verbetes: ["volatilidade", "dividendo", "risco-cambial", "diversificacao"],
    antecedentes: ["2000-bolha-pontocom", "1929-crash-de-nova-york"],
    noCurso: { modulo: 0, aula: 2, tempo: "56:28" },
    fonte: "Federal Reserve History, The Great Recession; S&P Dow Jones Indices",
  },
  {
    slug: "2008-whitepaper-do-bitcoin",
    ano: 2008,
    data: "31 de outubro de 2008",
    categoria: "Cripto",
    titulo: "O whitepaper do Bitcoin",
    resumo: "Em plena crise bancária, alguém com o nome de Satoshi Nakamoto publica a proposta de um dinheiro eletrônico sem intermediários.",
    texto: [
      "Em nove páginas, o texto resolve um problema antigo: como impedir que alguém gaste duas vezes o mesmo dinheiro digital sem um banco no meio. A resposta junta criptografia, um registro público encadeado e incentivos para quem valida as transações.",
      "O momento não foi acaso. Semanas antes, o Lehman tinha quebrado e governos socorriam bancos com dinheiro público.",
      "Por que importa hoje: o bitcoin nasceu como resposta à desconfiança no sistema financeiro. Se ele cabe ou não numa carteira, e com que tamanho, é tema do Módulo IV.",
    ],
    verbetes: ["bitcoin", "blockchain"],
    antecedentes: ["1993-manifesto-cypherpunk", "2008-quebra-do-lehman"],
    fonte: "S. Nakamoto, Bitcoin: A Peer-to-Peer Electronic Cash System",
  },
  {
    slug: "2008-juro-zero-e-qe",
    ano: 2008,
    data: "16 de dezembro de 2008",
    categoria: "Dinheiro e dólar",
    titulo: "Juro zero e a impressora do Fed",
    resumo: "O Fed leva os juros para entre zero e 0,25% e passa a comprar títulos em massa. Começa a década do dinheiro barato.",
    texto: [
      "Ben Bernanke, estudioso da Grande Depressão, não queria repetir os erros de 1929. Além do juro zero, o Fed comprou títulos do Tesouro e papéis imobiliários, o chamado afrouxamento quantitativo, para irrigar o sistema.",
      "O mundo rico viveu anos de juros reais perto de zero ou negativos. Com dinheiro barato, ações e imóveis subiram.",
      "Por que importa hoje: o juro americano é o piso do custo do dinheiro no mundo. A década de juro zero lá e juro alto aqui ajuda a explicar por que comparar só taxas engana: o retorno em reais depende também da moeda.",
    ],
    verbetes: ["banco-central", "juro-real", "treasury"],
    antecedentes: ["2008-quebra-do-lehman", "1979-choque-volcker"],
    noCurso: { modulo: 0, aula: 2, tempo: "56:28" },
    fonte: "Federal Reserve, comunicado do FOMC de 16/dez/2008",
  },
  {
    slug: "2009-bloco-genese",
    ano: 2009,
    data: "3 de janeiro de 2009",
    categoria: "Cripto",
    titulo: "O bloco gênese",
    resumo: "É criado o primeiro bloco do Bitcoin, com uma manchete de jornal sobre socorro a bancos gravada dentro dele.",
    texto: [
      "Dentro do bloco, Satoshi deixou a manchete do The Times daquele dia: o ministro britânico estava à beira de um segundo socorro aos bancos. Era um recado sobre o sistema que o bitcoin queria oferecer como alternativa.",
      "A rede começou a funcionar com quase ninguém olhando. O preço, nos primeiros meses, era praticamente zero.",
      "Por que importa hoje: a oferta do bitcoin é limitada a 21 milhões de unidades por regra do código. É essa escassez programada, num mundo de moedas sem lastro, que sustenta a tese de reserva de valor que o Módulo IV discute.",
    ],
    verbetes: ["bitcoin", "blockchain"],
    antecedentes: ["2008-whitepaper-do-bitcoin", "2008-juro-zero-e-qe"],
    fonte: "Blockchain do Bitcoin, bloco 0",
  },
  {
    slug: "2010-crise-do-euro",
    ano: 2010,
    data: "2 de maio de 2010",
    categoria: "Crises",
    titulo: "A crise do euro",
    resumo: "A Grécia recebe o primeiro pacote de socorro, de 110 bilhões de euros. A crise se espalha por Irlanda, Portugal, Espanha e Itália.",
    texto: [
      "A Grécia tinha escondido o tamanho do rombo e, sem moeda própria, não podia desvalorizar. Vieram socorros, cortes duros e, em 2012, os credores privados aceitaram perder mais da metade do valor de face dos títulos gregos.",
      "A virada veio em 26 de julho de 2012, quando Mario Draghi, do Banco Central Europeu, disse que faria o que fosse preciso para preservar o euro.",
      "Por que importa hoje: título de governo de país rico também pode dar perda. Diversificar entre moedas e emissores serve para isso, e nenhuma jurisdição é risco zero.",
    ],
    verbetes: ["divida-publica", "risco-pais", "banco-central"],
    antecedentes: ["1999-nasce-o-euro", "2008-quebra-do-lehman"],
    fonte: "Comissão Europeia; Banco Central Europeu",
  },
  {
    slug: "2010-pizza-de-bitcoin",
    ano: 2010,
    data: "22 de maio de 2010",
    categoria: "Cripto",
    titulo: "As pizzas de 10 mil bitcoins",
    resumo: "Um programador paga duas pizzas com 10 mil bitcoins. É a primeira compra conhecida de um bem físico com a moeda.",
    texto: [
      "Laszlo Hanyecz ofereceu os bitcoins num fórum, e alguém pediu as pizzas para ele. Na época, os 10 mil bitcoins valiam cerca de US$ 40. A data virou o Bitcoin Pizza Day.",
      "A anedota mostra duas coisas: o bitcoin precisou de alguém disposto a aceitá-lo para valer algo, e o preço dele subiu de forma extraordinária e com quedas enormes no caminho.",
      "Por que importa hoje: retornos passados espetaculares vêm com volatilidade espetacular. Quanto disso cabe na sua carteira é uma pergunta de tamanho de posição, não de entusiasmo.",
    ],
    verbetes: ["bitcoin", "volatilidade"],
    antecedentes: ["2009-bloco-genese"],
    fonte: "Fórum Bitcointalk",
  },
  {
    slug: "2012-alexnet",
    ano: 2012,
    data: "setembro de 2012",
    categoria: "Inteligência artificial",
    titulo: "AlexNet e a virada do aprendizado profundo",
    resumo: "Uma rede neural treinada em placas de vídeo vence o desafio ImageNet de reconhecimento de imagens com folga enorme.",
    texto: [
      "Alex Krizhevsky, Ilya Sutskever e Geoffrey Hinton treinaram a rede em duas placas da Nvidia feitas para jogos. O erro caiu para cerca de 15%, contra 26% do segundo colocado. Redes neurais, desacreditadas por anos, voltaram ao centro.",
      "O detalhe decisivo foi o hardware: as placas de vídeo viraram a máquina da inteligência artificial.",
      "Por que importa hoje: dessa virada saiu a demanda que transformou a Nvidia numa das maiores empresas do mundo. Saber de onde veio ajuda a entender por que poucas empresas de tecnologia pesam tanto no índice americano.",
    ],
    verbetes: ["inteligencia-artificial"],
    antecedentes: ["1997-deep-blue", "1956-conferencia-de-dartmouth"],
    fonte: "Krizhevsky, Sutskever e Hinton; resultados do ImageNet Challenge 2012",
  },
  {
    slug: "2014-primeira-stablecoin",
    ano: 2014,
    data: "6 de outubro de 2014",
    categoria: "Cripto",
    titulo: "Dólares numa blockchain",
    resumo: "São emitidos os primeiros tokens do que viria a ser o Tether, uma moeda digital que promete valer sempre um dólar.",
    texto: [
      "O projeto nasceu como Realcoin e logo virou Tether. A ideia era simples: para cada token, um dólar guardado em reserva. Assim, dava para mover dólares numa rede cripto, a qualquer hora, sem passar por banco.",
      "As stablecoins viraram um mercado de centenas de bilhões de dólares e uma porta de entrada para o dólar em países com moeda fraca.",
      "Por que importa hoje: a stablecoin é a forma mais direta de dólar digital, mas o valor dela depende da qualidade e da transparência da reserva. É a diferença entre dólar e promessa de dólar.",
    ],
    verbetes: ["stablecoin", "blockchain", "cambio"],
    antecedentes: ["2009-bloco-genese"],
    fonte: "Tether",
  },
  {
    slug: "2015-ethereum",
    ano: 2015,
    data: "30 de julho de 2015",
    categoria: "Cripto",
    titulo: "Ethereum",
    resumo: "Entra no ar a rede idealizada por Vitalik Buterin, uma blockchain que roda programas, os contratos inteligentes.",
    texto: [
      "O bitcoin registra quem tem quanto. O Ethereum foi além: permite escrever regras que se executam sozinhas na rede, como um empréstimo que libera a garantia quando a dívida é paga.",
      "Sobre essa ideia nasceram as finanças descentralizadas, boa parte das stablecoins e a tokenização de ativos tradicionais.",
      "Por que importa hoje: muito do que se discute sobre o futuro da infraestrutura financeira, de fundos tokenizados a pagamentos em stablecoin, roda nesse tipo de rede. O Módulo IV separa o que já funciona do que ainda é promessa.",
    ],
    verbetes: ["blockchain", "tokenizacao", "stablecoin"],
    antecedentes: ["2009-bloco-genese"],
    fonte: "Ethereum Foundation",
  },
  {
    slug: "2015-perda-do-grau-de-investimento",
    ano: 2015,
    data: "9 de setembro de 2015",
    categoria: "Brasil",
    titulo: "O Brasil perde o grau de investimento",
    resumo: "No meio da pior recessão em décadas, a S&P rebaixa o Brasil. Fitch e Moody's fazem o mesmo nos meses seguintes.",
    texto: [
      "O fim do boom das commodities, gastos subindo e o superávit virando déficit em 2014 cobraram a conta. O PIB caiu 3,5% em 2015 e 3,3% em 2016, e a Selic chegou a 14,25%.",
      "O selo conquistado em 2008 durou sete anos. Até hoje o Brasil não o recuperou.",
      "Por que importa hoje: recessão, juros, câmbio e bolsa reagiram juntos, porque respondiam à mesma causa. É o retrato do risco de concentração que o curso propõe diluir.",
    ],
    verbetes: ["risco-pais", "pib", "selic", "divida-publica"],
    antecedentes: ["2008-grau-de-investimento", "2001-china-na-omc"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:09:04" },
    fonte: "S&P Global Ratings; IBGE, Contas Nacionais",
  },
  {
    slug: "2016-alphago",
    ano: 2016,
    data: "15 de março de 2016",
    categoria: "Inteligência artificial",
    titulo: "AlphaGo vence no Go",
    resumo: "O programa da DeepMind derrota o sul-coreano Lee Sedol por 4 a 1 no jogo de tabuleiro mais complexo que existe.",
    texto: [
      "O Go tem mais posições possíveis do que a força bruta consegue calcular. O AlphaGo aprendeu jogando e combinou redes neurais com busca, e fez jogadas que os mestres chamaram de criativas.",
      "Especialistas esperavam esse resultado para dali a uma década. Ele veio antes.",
      "Por que importa hoje: a inteligência artificial costuma avançar mais rápido do que os especialistas preveem e mais devagar do que o mercado precifica no auge. Para o investidor, a tecnologia é real; o preço é que precisa de cuidado.",
    ],
    verbetes: ["inteligencia-artificial"],
    antecedentes: ["2012-alexnet"],
    fonte: "Google DeepMind",
  },
  {
    slug: "2016-teto-de-gastos",
    ano: 2016,
    data: "15 de dezembro de 2016",
    categoria: "Brasil",
    titulo: "O teto de gastos",
    resumo: "Uma emenda constitucional limita por 20 anos o crescimento da despesa federal à inflação.",
    texto: [
      "Depois do impeachment, a aposta foi em previsibilidade. O teto prometia que a despesa não cresceria acima da inflação, e o Banco Central levou a Selic de 14,25% para 6,5% em março de 2018.",
      "A regra foi furada várias vezes e, em agosto de 2023, deu lugar ao arcabouço fiscal, que limita o gasto a uma parte do crescimento da receita.",
      "Por que importa hoje: cada troca de regra fiscal reabre a dúvida sobre as contas públicas, e o mercado cobra no câmbio e nos juros longos. Acompanhar a regra em vigor faz parte de entender o risco Brasil.",
    ],
    verbetes: ["divida-publica", "selic", "risco-pais"],
    antecedentes: ["2015-perda-do-grau-de-investimento", "2000-lei-de-responsabilidade-fiscal"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:15:24" },
    fonte: "Emenda Constitucional 95/2016; Lei Complementar 200/2023",
  },
  {
    slug: "2017-joesley-day",
    ano: 2017,
    data: "18 de maio de 2017",
    categoria: "Crises",
    titulo: "O Joesley Day",
    resumo: "Uma gravação do presidente vem a público e a bolsa para por circuit breaker pela primeira vez desde 2008.",
    texto: [
      "Na noite de 17 de maio, foi revelada a gravação de Michel Temer feita pelo empresário Joesley Batista. No dia seguinte, com as reformas em dúvida, o Ibovespa chegou a cair mais de 10% e o pregão foi interrompido. O dólar subiu 8,8% e o risco-país saltou 42 pontos.",
      "Dali em diante, o governo gastou capital político para sobreviver, não para aprovar reformas.",
      "Por que importa hoje: na frase da aula, o risco político brasileiro não pode ser 100% do seu risco patrimonial. Uma gravação mexeu, num só dia, em câmbio, juros e bolsa.",
    ],
    verbetes: ["risco-pais", "ibovespa", "cambio", "embi"],
    antecedentes: ["2016-teto-de-gastos", "2015-perda-do-grau-de-investimento"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:17:30" },
    fonte: "B3; Banco Central do Brasil (SGS 1); JP Morgan, EMBI+, via IpeaData",
  },
  {
    slug: "2017-transformer",
    ano: 2017,
    data: "12 de junho de 2017",
    categoria: "Inteligência artificial",
    titulo: "Atenção é tudo de que você precisa",
    resumo: "Pesquisadores do Google publicam a arquitetura transformer, base dos grandes modelos de linguagem.",
    texto: [
      "O artigo propôs um jeito de a máquina ler um texto inteiro de uma vez, pesando a relação entre todas as palavras, em vez de ir palavra por palavra. Era mais rápido de treinar e escalava muito bem com mais dados e mais computação.",
      "Quase todos os grandes modelos de linguagem de hoje descendem dessa arquitetura.",
      "Por que importa hoje: a corrida que esse artigo iniciou move trilhões de dólares em investimento em chips, energia e data centers, quase tudo listado fora do Brasil.",
    ],
    verbetes: ["inteligencia-artificial"],
    antecedentes: ["2012-alexnet"],
    fonte: "Vaswani et al., Attention Is All You Need, arXiv",
  },
  {
    slug: "2019-corretagem-zero",
    ano: 2019,
    data: "1º de outubro de 2019",
    categoria: "Tecnologia e internet",
    titulo: "Corretagem zero",
    resumo: "A Charles Schwab zera a corretagem de ações e ETFs americanos, e as concorrentes vão atrás em dias.",
    texto: [
      "Aplicativos como o Robinhood já ofereciam corretagem zero. Quando uma das maiores corretoras tradicionais fez o mesmo, o custo de comprar uma ação nos Estados Unidos chegou a zero para quase todo mundo.",
      "O mesmo movimento chegou ao Brasil, com corretoras digitais e contas globais abertas pelo celular.",
      "Por que importa hoje: a barreira deixou de ser o custo de entrada e passou a ser de método. Corretagem zero não quer dizer custo zero: câmbio, IOF, taxas dos fundos e impostos continuam na conta.",
    ],
    verbetes: ["conta-global", "etf", "iof"],
    antecedentes: ["2007-iphone", "1975-fim-da-corretagem-fixa"],
    fonte: "Charles Schwab, comunicado de 1º/out/2019",
  },
  {
    slug: "2020-pandemia",
    ano: 2020,
    data: "11 de março de 2020",
    categoria: "Crises",
    titulo: "A pandemia",
    resumo: "A OMS declara a pandemia de covid-19. As bolsas despencam, a B3 interrompe os pregões várias vezes e o dólar chega a R$ 5,94 em maio.",
    texto: [
      "O S&P 500 perdeu cerca de um terço do valor em pouco mais de um mês, e alguns dos piores dias vieram colados aos melhores. No Brasil, o setor público fechou o ano com déficit de 9,2% do PIB, e o Banco Central levou a Selic a 2% em agosto.",
      "Com juro real negativo, o real perdeu o principal atrativo para o dinheiro de curto prazo. A inflação de 2021 fechou em 10,1%, e a Selic voltou a subir.",
      "Por que importa hoje: um evento sem relação com a sua carteira mexeu de uma vez em bolsa, câmbio e juros. Quem saiu do mercado no susto quase sempre perdeu a volta.",
    ],
    verbetes: ["volatilidade", "market-timing", "selic", "juro-real"],
    antecedentes: ["2008-quebra-do-lehman", "2017-joesley-day"],
    noCurso: { modulo: 0, aula: 2, tempo: "1:22:05" },
    fonte: "OMS; Banco Central do Brasil (SGS 1, 432 e 5793); S&P Dow Jones Indices",
  },
  {
    slug: "2020-defi",
    ano: 2020,
    categoria: "Cripto",
    titulo: "O verão das finanças descentralizadas",
    resumo: "Protocolos de empréstimo e troca sem intermediário explodem em uso sobre o Ethereum.",
    texto: [
      "Em meados de 2020, plataformas que emprestam, tomam emprestado e trocam ativos digitais por meio de contratos inteligentes atraíram bilhões de dólares em poucos meses. Ficou conhecido como o verão do DeFi.",
      "Também vieram fraudes, falhas de código e rendimentos que não se sustentavam.",
      "Por que importa hoje: DeFi mostra o que a infraestrutura cripto pode fazer e o tamanho dos riscos novos que ela traz, de código a governança. É assunto para estudar antes de alocar, como faz o Módulo IV.",
    ],
    verbetes: ["blockchain", "stablecoin", "volatilidade"],
    antecedentes: ["2015-ethereum", "2014-primeira-stablecoin"],
    fonte: "Ethereum Foundation",
  },
  {
    slug: "2020-bdr-para-todos",
    ano: 2020,
    data: "1º de setembro de 2020",
    categoria: "Investimentos",
    titulo: "BDRs para todo investidor",
    resumo: "Uma resolução da CVM libera os BDRs de ações estrangeiras para o investidor comum e abre espaço para BDRs de ETFs.",
    texto: [
      "Os BDRs, recibos negociados na B3 que representam ativos lá de fora, existiam desde 1996, mas os mais comuns eram restritos a investidores qualificados. A Resolução CVM 3, de agosto de 2020, abriu o acesso ao varejo e permitiu BDRs lastreados em cotas de ETFs.",
      "Pela primeira vez, dava para ter exposição a empresas e índices estrangeiros sem abrir conta fora, pela corretora de sempre e em reais.",
      "Por que importa hoje: o BDR é uma das portas de dolarização. Ele dá exposição ao ativo e ao câmbio, mas segue sob a regra e a custódia brasileiras. As diferenças em relação a uma conta lá fora estão no Módulo III.",
    ],
    verbetes: ["bdr", "etf", "risco-cambial"],
    antecedentes: ["1993-primeiro-etf", "1968-nasce-o-ibovespa"],
    noCurso: { modulo: 0, aula: 1 },
    fonte: "Resolução CVM 3/2020; Resolução CMN 2.318/1996",
  },
  {
    slug: "2020-pix",
    ano: 2020,
    data: "16 de novembro de 2020",
    categoria: "Brasil",
    titulo: "O Pix",
    resumo: "O Banco Central lança o seu sistema de pagamentos instantâneos, gratuito para pessoas físicas e disponível a qualquer hora.",
    texto: [
      "Em pouco tempo, o Pix virou o meio de pagamento mais usado do país em número de transações, à frente de cartões e boletos. Foi uma das maiores inovações financeiras do mundo naquela década, desenhada por um banco central.",
      "Junto com o open finance, mostrou que o Brasil pode ser vanguarda em infraestrutura financeira.",
      "Por que importa hoje: mover dinheiro ficou instantâneo e barato, e isso facilita também a ida até a conta global. O curso nunca foi sobre o Brasil dar errado: é sobre não depender de uma única caneta.",
    ],
    verbetes: ["banco-central", "conta-global"],
    antecedentes: ["2007-iphone", "1964-nasce-o-banco-central"],
    fonte: "Banco Central do Brasil",
  },
  {
    slug: "2022-reservas-russas-congeladas",
    ano: 2022,
    data: "28 de fevereiro de 2022",
    categoria: "Dinheiro e dólar",
    titulo: "As reservas da Rússia são congeladas",
    resumo: "Depois da invasão da Ucrânia, Estados Unidos e aliados bloqueiam cerca de metade das reservas internacionais do banco central russo.",
    texto: [
      "Cerca de US$ 300 bilhões em reservas guardadas no Ocidente ficaram inacessíveis da noite para o dia. Foi uma demonstração de que reservas em dólar, euro e outras moedas ocidentais dependem da relação com quem as emite.",
      "Desde então, vários bancos centrais aumentaram as compras de ouro, e a discussão sobre alternativas ao dólar ganhou força.",
      "Por que importa hoje: o dólar continua no centro do sistema, mas nenhuma moeda é neutra. Para o investidor pessoa física, a lição é a mesma do resto da linha: diversificar jurisdições, sem trocar uma concentração por outra.",
    ],
    verbetes: ["cambio", "banco-central", "diversificacao"],
    antecedentes: ["1944-bretton-woods", "1971-fim-do-padrao-dolar-ouro"],
    fonte: "Departamento do Tesouro dos EUA; FMI",
  },
  {
    slug: "2022-inflacao-e-alta-de-juros",
    ano: 2022,
    data: "16 de março de 2022",
    categoria: "Crises",
    titulo: "A volta da inflação",
    resumo: "O Fed começa o ciclo de alta de juros mais rápido em quatro décadas. Ações e títulos americanos caem juntos.",
    texto: [
      "Com a reabertura, cadeias travadas e a guerra na Ucrânia, a inflação americana chegou a 9,1% em 12 meses em junho. O Fed saiu de quase zero para mais de 4% até o fim do ano. O S&P 500 caiu cerca de 19% em 2022, e o título de 10 anos do Tesouro perdeu perto de 18%.",
      "Foi um dos piores anos da carteira 60/40, justamente porque a renda fixa, que costuma amortecer a bolsa, caiu junto.",
      "Por que importa hoje: título americano oscila de preço, e em choques de inflação pode cair junto com as ações. Entender isso é o ponto de partida do Módulo II, sobre Treasuries e o Fed.",
    ],
    verbetes: ["treasury", "carteira-60-40", "inflacao", "volatilidade"],
    antecedentes: ["2020-pandemia", "2008-juro-zero-e-qe", "1979-choque-volcker"],
    noCurso: { modulo: 0, aula: 3, tempo: "20:26" },
    fonte: "Federal Reserve; U.S. Bureau of Labor Statistics; S&P Dow Jones Indices",
  },
  {
    slug: "2022-merge",
    ano: 2022,
    data: "15 de setembro de 2022",
    categoria: "Cripto",
    titulo: "The Merge",
    resumo: "O Ethereum troca a mineração pela prova de participação e corta o consumo de energia da rede em mais de 99%.",
    texto: [
      "Em vez de máquinas gastando energia para validar blocos, a rede passou a ser protegida por quem deixa moedas travadas como garantia. A troca foi feita com a rede em funcionamento, como trocar o motor de um avião em pleno voo.",
      "O consumo de energia, uma das maiores críticas às redes cripto, caiu para uma fração mínima.",
      "Por que importa hoje: redes cripto mudam as próprias regras por consenso dos participantes. Isso traz flexibilidade e também um risco que não existe em ativos tradicionais, e entra na conta de quem estuda o setor.",
    ],
    verbetes: ["blockchain"],
    antecedentes: ["2015-ethereum"],
    fonte: "Ethereum Foundation",
  },
  {
    slug: "2022-colapso-da-ftx",
    ano: 2022,
    data: "11 de novembro de 2022",
    categoria: "Cripto",
    titulo: "O inverno cripto: Terra e FTX",
    resumo: "Depois do colapso da stablecoin algorítmica Terra, em maio, a corretora FTX pede falência. O mercado cripto perde boa parte do valor.",
    texto: [
      "A Terra prometia valer um dólar sem reserva em dólar, só por um mecanismo de mercado, e ruiu em dias. Meses depois, descobriu-se que a FTX, uma das maiores corretoras do mundo, usava o dinheiro dos clientes. Mais de um milhão de clientes ficaram com saldo preso.",
      "Não foi o bitcoin que falhou, mas os intermediários e as promessas em volta dele.",
      "Por que importa hoje: em cripto, quem guarda o ativo e onde ele está registrado importam tanto quanto o ativo. Custódia, regulação e reserva de verdade são as primeiras perguntas do Módulo IV.",
    ],
    verbetes: ["stablecoin", "bitcoin", "volatilidade"],
    antecedentes: ["2020-defi", "2014-primeira-stablecoin"],
    fonte: "Tribunal de falências de Delaware; SEC",
  },
  {
    slug: "2022-chatgpt",
    ano: 2022,
    data: "30 de novembro de 2022",
    categoria: "Inteligência artificial",
    titulo: "ChatGPT",
    resumo: "A OpenAI abre ao público um assistente de conversa. Em poucas semanas, a inteligência artificial generativa vira assunto de todo mundo.",
    texto: [
      "Pela primeira vez, qualquer pessoa podia conversar com um grande modelo de linguagem em linguagem comum, sem programar nada. O crescimento de usuários foi dos mais rápidos já vistos para um produto de tecnologia.",
      "Começou uma corrida de investimento em chips, data centers e energia que mudou o peso das empresas no índice americano.",
      "Por que importa hoje: a nova onda de inteligência artificial é um dos motores da bolsa americana e quase não tem representantes na B3. Ela também concentra o índice em poucas empresas, um risco a ter no radar.",
    ],
    verbetes: ["inteligencia-artificial", "sp-500"],
    antecedentes: ["2017-transformer", "2006-computacao-em-nuvem"],
    fonte: "OpenAI",
  },
  {
    slug: "2022-marco-legal-dos-criptoativos",
    ano: 2022,
    data: "21 de dezembro de 2022",
    categoria: "Cripto",
    titulo: "O marco legal dos criptoativos no Brasil",
    resumo: "A Lei 14.478 cria regras para as empresas que prestam serviços com ativos virtuais. O Banco Central vira o regulador.",
    texto: [
      "A lei entrou em vigor em junho de 2023, e um decreto daquele mês deu ao Banco Central a tarefa de regular o setor. As regras detalhadas saíram em novembro de 2025, com autorização obrigatória para as corretoras de cripto e normas de custódia.",
      "Depois da FTX, a pergunta deixou de ser se o setor seria regulado e passou a ser como.",
      "Por que importa hoje: regulação muda o risco de intermediário, que foi o que mais fez gente perder dinheiro em cripto. Também mexe no câmbio, porque operações com stablecoins passam a seguir regras de câmbio.",
    ],
    verbetes: ["bitcoin", "stablecoin", "banco-central"],
    antecedentes: ["2022-colapso-da-ftx"],
    fonte: "Lei 14.478/2022; Decreto 11.563/2023; Resoluções BCB 519, 520 e 521/2025",
  },
  {
    slug: "2022-marco-cambial",
    ano: 2022,
    data: "31 de dezembro de 2022",
    categoria: "Brasil",
    titulo: "O novo marco cambial",
    resumo: "Entra em vigor a Lei 14.286, que substitui um emaranhado de regras, algumas com quase um século, e simplifica o câmbio.",
    texto: [
      "A lei foi sancionada em dezembro de 2021 e passou a valer um ano depois. Consolidou normas espalhadas por dezenas de leis e decretos e deu ao Banco Central espaço para modernizar o câmbio e as contas em moeda estrangeira.",
      "Foi o pano de fundo para a expansão das contas globais de bancos e fintechs, abertas pelo celular e com valores pequenos.",
      "Por que importa hoje: investir lá fora deixou de exigir private banking e papelada. A barreira deixou de ser burocrática e passou a ser de método, e é para isso que serve o curso.",
    ],
    verbetes: ["marco-cambial", "conta-global", "cambio", "banco-central"],
    antecedentes: ["1999-cambio-flutuante", "2020-pix"],
    noCurso: { modulo: 0, aula: 1, tempo: "0:19" },
    fonte: "Lei 14.286/2021; Banco Central do Brasil",
  },
  {
    slug: "2023-quebra-do-svb",
    ano: 2023,
    data: "10 de março de 2023",
    categoria: "Crises",
    titulo: "A quebra do Silicon Valley Bank",
    resumo: "Uma corrida digital derruba em dois dias o banco das startups americanas. Outros bancos regionais caem nas semanas seguintes.",
    texto: [
      "O SVB tinha aplicado os depósitos em títulos longos, que perderam valor com a alta dos juros. Quando a notícia correu pelas redes, os clientes tentaram sacar dezenas de bilhões de dólares num dia, pelo celular. O banco foi fechado, e o governo garantiu todos os depósitos. Em maio, foi a vez do First Republic.",
      "Foi a primeira corrida bancária da era dos aplicativos.",
      "Por que importa hoje: título do Tesouro americano é seguro contra calote, mas o preço oscila com os juros. E onde o seu dinheiro fica custodiado lá fora importa: proteção a depósitos e a investimentos são coisas diferentes, tema do Módulo III.",
    ],
    verbetes: ["treasury", "volatilidade", "conta-global"],
    antecedentes: ["2022-inflacao-e-alta-de-juros"],
    fonte: "FDIC; Federal Reserve",
  },
  {
    slug: "2023-lei-14754",
    ano: 2023,
    data: "12 de dezembro de 2023",
    categoria: "Brasil",
    titulo: "A nova tributação dos investimentos lá fora",
    resumo: "A Lei 14.754 passa a tributar em 15%, na declaração anual, o ganho da pessoa física com aplicações no exterior.",
    texto: [
      "A regra vale desde 1º de janeiro de 2024 e unificou o tratamento de ganhos, juros e dividendos de aplicações financeiras no exterior. O cálculo é feito em reais, e isso tem uma consequência: a variação do câmbio entra na conta.",
      "Se você vende um ativo pelo mesmo preço em dólar que pagou, mas o dólar subiu, paga imposto sobre um ganho que, em dólar, não existiu.",
      "Por que importa hoje: o imposto muda a comparação entre investir direto lá fora, por BDR ou por ETF local. Os detalhes, exceções e compensação de perdas ficam para o Módulo III, e devem ser sempre conferidos na regra em vigor.",
    ],
    verbetes: ["lei-14754", "risco-cambial", "conta-global", "bdr"],
    antecedentes: ["2022-marco-cambial"],
    noCurso: { modulo: 0, aula: 1, tempo: "35:56" },
    fonte: "Lei 14.754/2023",
  },
  {
    slug: "2024-etfs-de-bitcoin-a-vista",
    ano: 2024,
    data: "10 de janeiro de 2024",
    categoria: "Cripto",
    titulo: "Os ETFs de bitcoin à vista nos EUA",
    resumo: "A SEC aprova onze ETFs que compram bitcoin de verdade. A negociação começa no dia seguinte.",
    texto: [
      "Depois de mais de uma década de pedidos negados, o regulador americano liberou fundos que guardam o próprio bitcoin, e não contratos futuros. Grandes gestoras tradicionais entraram no mercado, e os fundos atraíram dezenas de bilhões de dólares no primeiro ano.",
      "O ativo criado por anônimos em 2009 passou a ser comprado como qualquer ETF, na conta da corretora.",
      "Por que importa hoje: o ETF resolve parte do risco de custódia e torna o bitcoin acessível dentro da estrutura regulada. Não muda a volatilidade do ativo, e o tamanho da posição continua sendo a decisão principal.",
    ],
    verbetes: ["bitcoin", "etf", "volatilidade"],
    antecedentes: ["2009-bloco-genese", "1993-primeiro-etf", "2022-colapso-da-ftx"],
    fonte: "SEC, aprovação de 10/jan/2024",
  },
  {
    slug: "2024-fundo-tokenizado",
    ano: 2024,
    data: "março de 2024",
    categoria: "Cripto",
    titulo: "Títulos do Tesouro numa blockchain",
    resumo: "A BlackRock, maior gestora do mundo, lança no Ethereum um fundo tokenizado que aplica em títulos do Tesouro americano e caixa.",
    texto: [
      "Cada cota do fundo é um token numa blockchain, com rendimento pago diretamente na carteira digital do investidor. O fundo, voltado a investidores qualificados, aplica em caixa, títulos curtos do Tesouro e operações compromissadas.",
      "A tokenização de ativos reais, como títulos, fundos e imóveis, saiu do discurso e entrou nas grandes gestoras.",
      "Por que importa hoje: a mesma renda fixa americana do Módulo II pode passar a circular em novas infraestruturas. A tecnologia muda o trilho, não o risco do ativo que está por trás.",
    ],
    verbetes: ["tokenizacao", "treasury", "blockchain"],
    antecedentes: ["2015-ethereum", "2014-primeira-stablecoin"],
    fonte: "BlackRock, comunicado de março de 2024",
  },
  {
    slug: "2025-iof-por-decreto",
    ano: 2025,
    data: "22 de maio de 2025",
    categoria: "Brasil",
    titulo: "O IOF muda por decreto",
    resumo: "Um decreto sobe o IOF sobre câmbio e outras operações. O Congresso derruba, e o STF restabelece quase tudo em julho.",
    texto: [
      "Em 2022, um decreto tinha prometido zerar o IOF sobre câmbio até 2029. Em 2025, decretos de maio e junho desfizeram a promessa. O Congresso sustou a mudança no fim de junho, e uma decisão do ministro Alexandre de Moraes, em 16 de julho, devolveu a validade a quase todo o aumento.",
      "Hoje, mandar dinheiro para investir lá fora em seu próprio nome paga 1,1%; comprar dólar em espécie e gastar no cartão internacional pagam 3,5%.",
      "Por que importa hoje: o IOF pode mudar com efeito imediato, sem votação. É um custo de ida que entra na conta de quem dolariza, e um exemplo de regra que muda no meio do jogo.",
    ],
    verbetes: ["iof", "cambio", "conta-global"],
    antecedentes: ["2022-marco-cambial", "2023-lei-14754"],
    noCurso: { modulo: 0, aula: 1, tempo: "35:56" },
    fonte: "Decretos 12.466 e 12.499/2025; Decreto Legislativo 176/2025; STF, ADC 96",
  },
  {
    slug: "2025-genius-act",
    ano: 2025,
    data: "18 de julho de 2025",
    categoria: "Cripto",
    titulo: "Os Estados Unidos regulam as stablecoins",
    resumo: "A lei GENIUS cria regras federais para stablecoins de pagamento, com reserva de um para um em ativos líquidos.",
    texto: [
      "A lei exige que as stablecoins em dólar tenham reservas equivalentes em dinheiro, depósitos e títulos curtos do Tesouro americano, com divulgação periódica. Emissores passam a ser supervisionados.",
      "Na prática, as stablecoins viram um canal regulado de demanda por dólares e por títulos do Tesouro.",
      "Por que importa hoje: o dólar digital ganhou regra no país que emite o dólar. Isso reforça o papel da moeda americana na nova infraestrutura financeira e separa as stablecoins com reserva de verdade das promessas.",
    ],
    verbetes: ["stablecoin", "treasury", "tokenizacao"],
    antecedentes: ["2014-primeira-stablecoin", "2022-colapso-da-ftx"],
    fonte: "GENIUS Act; Casa Branca",
  },
  {
    slug: "2025-nvidia-5-trilhoes",
    ano: 2025,
    data: "29 de outubro de 2025",
    categoria: "Inteligência artificial",
    titulo: "Uma empresa maior que a bolsa brasileira",
    resumo: "A Nvidia, fabricante dos chips que treinam a inteligência artificial, é a primeira empresa a valer US$ 5 trilhões.",
    texto: [
      "As placas de vídeo que treinaram a AlexNet em 2012 viraram o insumo mais disputado da nova onda de inteligência artificial. Em outubro de 2025, a Nvidia passou dos US$ 5 trilhões em valor de mercado, mais do que todas as empresas da B3 juntas.",
      "Ao mesmo tempo, o S&P 500 ficou mais concentrado: poucas empresas de tecnologia passaram a responder por uma fatia enorme do índice.",
      "Por que importa hoje: a escala do mercado americano é outra, e a tecnologia que define a década está lá. Mas concentração também é risco: dolarizar não é trocar uma aposta concentrada por outra.",
    ],
    verbetes: ["inteligencia-artificial", "sp-500", "diversificacao", "home-bias"],
    antecedentes: ["2022-chatgpt", "2012-alexnet"],
    noCurso: { modulo: 0, aula: 4, tempo: "8:05" },
    fonte: "Nasdaq; B3",
  },
  {
    slug: "2025-dolar-nas-reservas",
    ano: 2025,
    data: "fim de 2025",
    categoria: "Dinheiro e dólar",
    titulo: "O dólar ainda é a régua do mundo",
    resumo: "Pelos dados do FMI, perto de 57% das reservas cambiais dos bancos centrais estão em dólar. O euro, segundo colocado, fica perto de 20%.",
    texto: [
      "A fatia do dólar nas reservas caiu devagar, de cerca de 71% em 1999 para perto de 57% no fim de 2025, a menor em três décadas. Ouro e moedas menores ganharam espaço. Mesmo assim, nenhuma outra moeda chega perto, e o comércio, a dívida e as commodities do mundo seguem cotados em dólar.",
      "Previsões do fim do dólar existem desde Triffin. Até agora, a mudança tem sido lenta e parcial.",
      "Por que importa hoje: guardar parte do patrimônio em dólar é usar a moeda que melhor cumpre as três funções do dinheiro no mundo, guardar valor, servir de régua e ser aceita em qualquer mercado. É diversificação, não aposta contra o real.",
    ],
    verbetes: ["cambio", "bretton-woods", "treasury", "diversificacao"],
    antecedentes: ["2022-reservas-russas-congeladas", "1999-nasce-o-euro", "1944-bretton-woods"],
    noCurso: { modulo: 0, aula: 1, tempo: "3:49" },
    fonte: "FMI, COFER (Currency Composition of Official Foreign Exchange Reserves)",
  },
];
